// Copyright 2025 Confluent Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Configuration for the Kafka Producer.
//!
//! Translated from `org.apache.kafka.clients.producer.ProducerConfig`.
//!
//! This is a Rust struct with named fields rather than the Java `ConfigDef`
//! reflection framework. The field names and default values match the Java
//! config keys.

use crate::common::record::CompressionType;

/// Maximum number of in-flight requests per connection when idempotence is enabled.
/// Aligned with `ProducerStateEntry.NUM_BATCHES_TO_RETAIN` on the broker.
const MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION_FOR_IDEMPOTENCE: i32 = 5;

/// Configuration for the Kafka Producer.
///
/// Documentation for these configurations can be found in the
/// [Kafka documentation](http://kafka.apache.org/documentation.html#producerconfigs).
///
/// Corresponds to `org.apache.kafka.clients.producer.ProducerConfig`.
#[derive(Clone, Debug)]
pub struct ProducerConfig {
    // --- Connection ---
    /// `bootstrap.servers` - A list of host/port pairs to use for establishing the
    /// initial connection to the Kafka cluster.
    pub bootstrap_servers: Vec<String>,

    /// `client.id` - An id string to pass to the server when making requests.
    pub client_id: String,

    // --- Batching ---
    /// `batch.size` - The producer will attempt to batch records together into fewer
    /// requests whenever multiple records are being sent to the same partition.
    /// Default: 16384 bytes.
    pub batch_size: i32,

    /// `linger.ms` - Upper bound on the delay for batching.
    /// Default: 5 ms (changed from 0 in Apache Kafka 4.0).
    pub linger_ms: i64,

    // --- Buffering ---
    /// `buffer.memory` - Total bytes of memory the producer can use to buffer records
    /// waiting to be sent. Default: 32 MiB.
    pub buffer_memory: i64,

    /// `max.block.ms` - Maximum time `send()` and `partitionsFor()` will block.
    /// Default: 60000 ms.
    pub max_block_ms: i64,

    // --- Reliability ---
    /// `acks` - Number of acknowledgments the producer requires the leader to have
    /// received. Allowed values: 0, 1, -1 (all). Default: -1 (all).
    pub acks: i16,

    /// `retries` - Number of times to retry a request that fails with a transient error.
    /// Default: `i32::MAX` (effectively infinite retries bounded by delivery timeout).
    pub retries: i32,

    /// `delivery.timeout.ms` - Upper bound on time to report success or failure after
    /// `send()` returns. Default: 120000 ms.
    pub delivery_timeout_ms: i32,

    /// `request.timeout.ms` - Maximum time the client will wait for a response.
    /// Default: 30000 ms.
    pub request_timeout_ms: i32,

    /// `enable.idempotence` - When true, exactly-once delivery semantics are enabled.
    /// Default: true.
    pub enable_idempotence: bool,

    // --- Sizing ---
    /// `max.request.size` - Maximum size of a request in bytes.
    /// Default: 1048576 (1 MiB).
    pub max_request_size: i32,

    /// `max.in.flight.requests.per.connection` - Maximum number of unacknowledged
    /// requests per connection. Default: 5.
    pub max_in_flight_requests_per_connection: i32,

    // --- Compression ---
    /// `compression.type` - Compression type for all data generated by the producer.
    /// Default: `CompressionType::None`.
    pub compression_type: CompressionType,

    // --- Connections ---
    /// `connections.max.idle.ms` - Close idle connections after this duration.
    /// Default: 540000 ms (9 minutes).
    pub connections_max_idle_ms: i64,

    /// `reconnect.backoff.ms` - Base wait time before attempting to reconnect.
    /// Default: 50 ms.
    pub reconnect_backoff_ms: i64,

    /// `reconnect.backoff.max.ms` - Maximum wait time before reconnection attempts.
    /// Default: 1000 ms.
    pub reconnect_backoff_max_ms: i64,

    /// `retry.backoff.ms` - Wait time before retrying a failed request.
    /// Default: 100 ms.
    pub retry_backoff_ms: i64,

    /// `retry.backoff.max.ms` - Maximum wait time before retrying a failed request.
    /// Default: 1000 ms.
    pub retry_backoff_max_ms: i64,

    // --- Socket ---
    /// `send.buffer.bytes` - TCP send buffer size. Default: 131072 (128 KiB).
    pub send_buffer_bytes: i32,

    /// `receive.buffer.bytes` - TCP receive buffer size. Default: 32768 (32 KiB).
    pub receive_buffer_bytes: i32,

    /// `socket.connection.setup.timeout.ms` - Timeout for socket connection setup.
    /// Default: 10000 ms.
    pub socket_connection_setup_timeout_ms: i64,

    /// `socket.connection.setup.timeout.max.ms` - Maximum timeout for socket connection
    /// setup. Default: 30000 ms.
    pub socket_connection_setup_timeout_max_ms: i64,

    // --- Metadata ---
    /// `metadata.max.age.ms` - Period after which metadata is force-refreshed.
    /// Default: 300000 ms (5 minutes).
    pub metadata_max_age_ms: i64,

    /// `metadata.max.idle.ms` - Controls how long the producer will cache metadata for
    /// an idle topic. Default: 300000 ms (5 minutes).
    pub metadata_max_idle_ms: i64,

    // --- Partitioning ---
    /// `partitioner.adaptive.partitioning.enable` - Adapt to broker performance.
    /// Default: true.
    pub partitioner_adaptive_partitioning_enable: bool,

    /// `partitioner.availability.timeout.ms` - Timeout to mark a partition as
    /// unavailable. Default: 0 (disabled).
    pub partitioner_availability_timeout_ms: i64,

    /// `partitioner.ignore.keys` - Ignore record keys for partitioning.
    /// Default: false.
    pub partitioner_ignore_keys: bool,

    // --- Transactions ---
    /// `transactional.id` - TransactionalId for transactional delivery.
    /// Default: `None` (no transactions).
    pub transactional_id: Option<String>,

    /// `transaction.timeout.ms` - Maximum time a transaction will remain open.
    /// Default: 60000 ms.
    pub transaction_timeout_ms: i32,
}

impl Default for ProducerConfig {
    fn default() -> Self {
        Self {
            bootstrap_servers: Vec::new(),
            client_id: String::new(),
            batch_size: 16384,
            linger_ms: 5,
            buffer_memory: 32 * 1024 * 1024,
            max_block_ms: 60 * 1000,
            acks: -1, // "all"
            retries: i32::MAX,
            delivery_timeout_ms: 120 * 1000,
            request_timeout_ms: 30 * 1000,
            enable_idempotence: true,
            max_request_size: 1024 * 1024,
            max_in_flight_requests_per_connection: 5,
            compression_type: CompressionType::None,
            connections_max_idle_ms: 9 * 60 * 1000,
            reconnect_backoff_ms: 50,
            reconnect_backoff_max_ms: 1000,
            retry_backoff_ms: 100,
            retry_backoff_max_ms: 1000,
            send_buffer_bytes: 128 * 1024,
            receive_buffer_bytes: 32 * 1024,
            socket_connection_setup_timeout_ms: 10_000,
            socket_connection_setup_timeout_max_ms: 30_000,
            metadata_max_age_ms: 5 * 60 * 1000,
            metadata_max_idle_ms: 5 * 60 * 1000,
            partitioner_adaptive_partitioning_enable: true,
            partitioner_availability_timeout_ms: 0,
            partitioner_ignore_keys: false,
            transactional_id: None,
            transaction_timeout_ms: 60_000,
        }
    }
}

impl ProducerConfig {
    /// Creates a new `ProducerConfig` with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Maximum number of in-flight requests per connection when idempotence is enabled.
    pub const MAX_IN_FLIGHT_REQUESTS_FOR_IDEMPOTENCE: i32 = MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION_FOR_IDEMPOTENCE;

    // --- Config key constants (matching Java string keys) ---

    /// Config key: `bootstrap.servers`
    pub const BOOTSTRAP_SERVERS_CONFIG: &'static str = "bootstrap.servers";
    /// Config key: `client.id`
    pub const CLIENT_ID_CONFIG: &'static str = "client.id";
    /// Config key: `batch.size`
    pub const BATCH_SIZE_CONFIG: &'static str = "batch.size";
    /// Config key: `linger.ms`
    pub const LINGER_MS_CONFIG: &'static str = "linger.ms";
    /// Config key: `buffer.memory`
    pub const BUFFER_MEMORY_CONFIG: &'static str = "buffer.memory";
    /// Config key: `max.block.ms`
    pub const MAX_BLOCK_MS_CONFIG: &'static str = "max.block.ms";
    /// Config key: `acks`
    pub const ACKS_CONFIG: &'static str = "acks";
    /// Config key: `retries`
    pub const RETRIES_CONFIG: &'static str = "retries";
    /// Config key: `delivery.timeout.ms`
    pub const DELIVERY_TIMEOUT_MS_CONFIG: &'static str = "delivery.timeout.ms";
    /// Config key: `request.timeout.ms`
    pub const REQUEST_TIMEOUT_MS_CONFIG: &'static str = "request.timeout.ms";
    /// Config key: `enable.idempotence`
    pub const ENABLE_IDEMPOTENCE_CONFIG: &'static str = "enable.idempotence";
    /// Config key: `max.request.size`
    pub const MAX_REQUEST_SIZE_CONFIG: &'static str = "max.request.size";
    /// Config key: `max.in.flight.requests.per.connection`
    pub const MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION: &'static str = "max.in.flight.requests.per.connection";
    /// Config key: `compression.type`
    pub const COMPRESSION_TYPE_CONFIG: &'static str = "compression.type";
    /// Config key: `connections.max.idle.ms`
    pub const CONNECTIONS_MAX_IDLE_MS_CONFIG: &'static str = "connections.max.idle.ms";
    /// Config key: `reconnect.backoff.ms`
    pub const RECONNECT_BACKOFF_MS_CONFIG: &'static str = "reconnect.backoff.ms";
    /// Config key: `reconnect.backoff.max.ms`
    pub const RECONNECT_BACKOFF_MAX_MS_CONFIG: &'static str = "reconnect.backoff.max.ms";
    /// Config key: `retry.backoff.ms`
    pub const RETRY_BACKOFF_MS_CONFIG: &'static str = "retry.backoff.ms";
    /// Config key: `retry.backoff.max.ms`
    pub const RETRY_BACKOFF_MAX_MS_CONFIG: &'static str = "retry.backoff.max.ms";
    /// Config key: `send.buffer.bytes`
    pub const SEND_BUFFER_CONFIG: &'static str = "send.buffer.bytes";
    /// Config key: `receive.buffer.bytes`
    pub const RECEIVE_BUFFER_CONFIG: &'static str = "receive.buffer.bytes";
    /// Config key: `metadata.max.age.ms`
    pub const METADATA_MAX_AGE_CONFIG: &'static str = "metadata.max.age.ms";
    /// Config key: `metadata.max.idle.ms`
    pub const METADATA_MAX_IDLE_CONFIG: &'static str = "metadata.max.idle.ms";
    /// Config key: `partitioner.adaptive.partitioning.enable`
    pub const PARTITIONER_ADAPTIVE_PARTITIONING_ENABLE_CONFIG: &'static str =
        "partitioner.adaptive.partitioning.enable";
    /// Config key: `partitioner.availability.timeout.ms`
    pub const PARTITIONER_AVAILABILITY_TIMEOUT_MS_CONFIG: &'static str = "partitioner.availability.timeout.ms";
    /// Config key: `partitioner.ignore.keys`
    pub const PARTITIONER_IGNORE_KEYS_CONFIG: &'static str = "partitioner.ignore.keys";
    /// Config key: `transactional.id`
    pub const TRANSACTIONAL_ID_CONFIG: &'static str = "transactional.id";
    /// Config key: `transaction.timeout.ms`
    pub const TRANSACTION_TIMEOUT_CONFIG: &'static str = "transaction.timeout.ms";

    /// Parses the acks string, converting "all" to -1.
    pub fn parse_acks(acks_string: &str) -> Result<i16, String> {
        let trimmed = acks_string.trim();
        if trimmed.eq_ignore_ascii_case("all") {
            Ok(-1)
        } else {
            trimmed
                .parse::<i16>()
                .map_err(|_| format!("Invalid configuration value for 'acks': {acks_string}"))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_values() {
        let config = ProducerConfig::default();
        assert_eq!(config.batch_size, 16384);
        assert_eq!(config.linger_ms, 5);
        assert_eq!(config.buffer_memory, 32 * 1024 * 1024);
        assert_eq!(config.max_block_ms, 60_000);
        assert_eq!(config.acks, -1);
        assert_eq!(config.retries, i32::MAX);
        assert_eq!(config.delivery_timeout_ms, 120_000);
        assert_eq!(config.request_timeout_ms, 30_000);
        assert!(config.enable_idempotence);
        assert_eq!(config.max_request_size, 1_048_576);
        assert_eq!(config.max_in_flight_requests_per_connection, 5);
        assert_eq!(config.compression_type, CompressionType::None);
        assert_eq!(config.connections_max_idle_ms, 540_000);
        assert_eq!(config.reconnect_backoff_ms, 50);
        assert_eq!(config.reconnect_backoff_max_ms, 1000);
        assert_eq!(config.retry_backoff_ms, 100);
        assert_eq!(config.retry_backoff_max_ms, 1000);
        assert_eq!(config.send_buffer_bytes, 131_072);
        assert_eq!(config.receive_buffer_bytes, 32_768);
        assert_eq!(config.metadata_max_age_ms, 300_000);
        assert_eq!(config.metadata_max_idle_ms, 300_000);
        assert!(config.partitioner_adaptive_partitioning_enable);
        assert_eq!(config.partitioner_availability_timeout_ms, 0);
        assert!(!config.partitioner_ignore_keys);
        assert!(config.transactional_id.is_none());
        assert_eq!(config.transaction_timeout_ms, 60_000);
    }

    #[test]
    fn test_parse_acks() {
        assert_eq!(ProducerConfig::parse_acks("all"), Ok(-1));
        assert_eq!(ProducerConfig::parse_acks("ALL"), Ok(-1));
        assert_eq!(ProducerConfig::parse_acks("-1"), Ok(-1));
        assert_eq!(ProducerConfig::parse_acks("0"), Ok(0));
        assert_eq!(ProducerConfig::parse_acks("1"), Ok(1));
        assert!(ProducerConfig::parse_acks("invalid").is_err());
    }
}
