// Copyright 2025 Confluent Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Configuration for the Kafka Producer.
//!
//! Translated from `org.apache.kafka.clients.producer.ProducerConfig`.
//!
//! This is a Rust struct with named fields rather than the Java `ConfigDef`
//! reflection framework. The field names and default values match the Java
//! config keys.

use std::collections::{HashMap, HashSet};
use std::sync::atomic::{self, AtomicI32};

use log::{info, warn};

use crate::common::Error;
use crate::common::config::sasl_configs;
use crate::common::config::ssl_configs;
use crate::common::config::{SaslConfig, SslConfig};
use crate::common::record::CompressionType;
use crate::common::security::SecurityProtocol;
use crate::common_client_configs;

/// Process-wide counter for deriving a default `client.id`.
///
/// Corresponds to Java's `static AtomicInteger PRODUCER_CLIENT_ID_SEQUENCE`,
/// which starts at 1. Crate-level (not per-config) to match Java's static scope,
/// so successive producers in one process get distinct ids.
static PRODUCER_CLIENT_ID_SEQUENCE: AtomicI32 = AtomicI32::new(1);

/// Maximum number of in-flight requests per connection when idempotence is enabled.
/// Aligned with `ProducerStateEntry.NUM_BATCHES_TO_RETAIN` on the broker.
const MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION_FOR_IDEMPOTENCE: i32 = 5;

/// Configuration for the Kafka Producer.
///
/// Documentation for these configurations can be found in the
/// [Kafka documentation](http://kafka.apache.org/documentation.html#producerconfigs).
///
/// Corresponds to `org.apache.kafka.clients.producer.ProducerConfig`.
#[derive(Clone, Debug)]
pub struct ProducerConfig {
    // --- Connection ---
    /// `bootstrap.servers` - A list of host/port pairs to use for establishing the
    /// initial connection to the Kafka cluster.
    pub(crate) bootstrap_servers: Vec<String>,

    /// `client.id` - An id string to pass to the server when making requests.
    pub(crate) client_id: String,

    // --- Security ---
    /// `security.protocol` - Protocol used to communicate with brokers.
    /// Default: `SecurityProtocol::Plaintext`.
    pub(crate) security_protocol: SecurityProtocol,

    /// SASL configuration (mechanism, JAAS config, credentials).
    pub(crate) sasl_config: SaslConfig,

    /// SSL/TLS configuration.
    pub(crate) ssl_config: SslConfig,

    // --- Batching ---
    /// `batch.size` - The producer will attempt to batch records together into fewer
    /// requests whenever multiple records are being sent to the same partition.
    /// Default: 16384 bytes.
    pub(crate) batch_size: i32,

    /// `linger.ms` - Upper bound on the delay for batching.
    /// Default: 5 ms (changed from 0 in Apache Kafka 4.0).
    pub(crate) linger_ms: i64,

    // --- Buffering ---
    /// `buffer.memory` - Total bytes of memory the producer can use to buffer records
    /// waiting to be sent. Default: 32 MiB.
    pub(crate) buffer_memory: i64,

    /// `max.block.ms` - Maximum time `send()` and `partitionsFor()` will block.
    /// Default: 60000 ms.
    pub(crate) max_block_ms: i64,

    // --- Reliability ---
    /// `acks` - Number of acknowledgments the producer requires the leader to have
    /// received. Allowed values: 0, 1, -1 (all). Default: -1 (all).
    pub(crate) acks: i16,

    /// `retries` - Number of times to retry a request that fails with a transient error.
    /// Default: `i32::MAX` (effectively infinite retries bounded by delivery timeout).
    pub(crate) retries: i32,

    /// `delivery.timeout.ms` - Upper bound on time to report success or failure after
    /// `send()` returns. Default: 120000 ms.
    pub(crate) delivery_timeout_ms: i32,

    /// `request.timeout.ms` - Maximum time the client will wait for a response.
    /// Default: 30000 ms.
    pub(crate) request_timeout_ms: i32,

    /// `enable.idempotence` - When true, exactly-once delivery semantics are enabled.
    /// Default: true.
    pub(crate) enable_idempotence: bool,

    // --- Sizing ---
    /// `max.request.size` - Maximum size of a request in bytes.
    /// Default: 1048576 (1 MiB).
    pub(crate) max_request_size: i32,

    /// `max.in.flight.requests.per.connection` - Maximum number of unacknowledged
    /// requests per connection. Default: 5.
    pub(crate) max_in_flight_requests_per_connection: i32,

    // --- Compression ---
    /// `compression.type` - Compression type for all data generated by the producer.
    /// Default: `CompressionType::None`.
    pub(crate) compression_type: CompressionType,

    // --- Connections ---
    /// `connections.max.idle.ms` - Close idle connections after this duration.
    /// Default: 540000 ms (9 minutes).
    pub(crate) connections_max_idle_ms: i64,

    /// `reconnect.backoff.ms` - Base wait time before attempting to reconnect.
    /// Default: 50 ms.
    pub(crate) reconnect_backoff_ms: i64,

    /// `reconnect.backoff.max.ms` - Maximum wait time before reconnection attempts.
    /// Default: 1000 ms.
    pub(crate) reconnect_backoff_max_ms: i64,

    /// `retry.backoff.ms` - Wait time before retrying a failed request.
    /// Default: 100 ms.
    pub(crate) retry_backoff_ms: i64,

    /// `retry.backoff.max.ms` - Maximum wait time before retrying a failed request.
    /// Default: 1000 ms.
    pub(crate) retry_backoff_max_ms: i64,

    // --- Socket ---
    /// `send.buffer.bytes` - TCP send buffer size. Default: 131072 (128 KiB).
    pub(crate) send_buffer_bytes: i32,

    /// `receive.buffer.bytes` - TCP receive buffer size. Default: 32768 (32 KiB).
    pub(crate) receive_buffer_bytes: i32,

    /// `socket.connection.setup.timeout.ms` - Timeout for socket connection setup.
    /// Default: 10000 ms.
    pub(crate) socket_connection_setup_timeout_ms: i64,

    /// `socket.connection.setup.timeout.max.ms` - Maximum timeout for socket connection
    /// setup. Default: 30000 ms.
    pub(crate) socket_connection_setup_timeout_max_ms: i64,

    // --- Metadata ---
    /// `metadata.max.age.ms` - Period after which metadata is force-refreshed.
    /// Default: 300000 ms (5 minutes).
    pub(crate) metadata_max_age_ms: i64,

    /// `metadata.max.idle.ms` - Controls how long the producer will cache metadata for
    /// an idle topic. Default: 300000 ms (5 minutes).
    pub(crate) metadata_max_idle_ms: i64,

    // --- Partitioning ---
    /// `partitioner.adaptive.partitioning.enable` - Adapt to broker performance.
    /// Default: true.
    pub(crate) partitioner_adaptive_partitioning_enable: bool,

    /// `partitioner.availability.timeout.ms` - Timeout to mark a partition as
    /// unavailable. Default: 0 (disabled).
    pub(crate) partitioner_availability_timeout_ms: i64,

    /// `partitioner.ignore.keys` - Ignore record keys for partitioning.
    /// Default: false.
    pub(crate) partitioner_ignore_keys: bool,

    // --- Transactions ---
    /// `transactional.id` - TransactionalId for transactional delivery.
    /// Default: `None` (no transactions).
    pub(crate) transactional_id: Option<String>,

    /// `transaction.timeout.ms` - Maximum time a transaction will remain open.
    /// Default: 60000 ms.
    pub(crate) transaction_timeout_ms: i32,

    /// `transaction.two.phase.commit.enable` - Whether the client participates
    /// in two-phase commit (KIP-939), where an external coordinator decides when
    /// to finalize. Default: `false`.
    pub(crate) two_phase_commit_enable: bool,

    /// Keys the user set explicitly, as opposed to keys left at their default.
    ///
    /// Replaces Java's `AbstractConfig.originals().containsKey(..)`, which this
    /// codebase has no equivalent of. Java's idempotence validation behaves
    /// differently depending on whether the user *asked* for a setting or merely
    /// inherited the default: an explicit `enable.idempotence=true` alongside
    /// `retries=0` is a `ConfigException`, while the same combination reached by
    /// default silently disables idempotence.
    ///
    /// `pub(crate)` like every other field on this struct, so in-crate struct
    /// literals using `..Default::default()` still compile. It is an
    /// implementation detail of validation and is not part of the public API.
    pub(crate) explicitly_set: HashSet<String>,
}

impl Default for ProducerConfig {
    fn default() -> Self {
        Self {
            bootstrap_servers: Vec::new(),
            client_id: String::new(),
            security_protocol: SecurityProtocol::Plaintext,
            sasl_config: SaslConfig::default(),
            ssl_config: SslConfig::default(),
            batch_size: 16384,
            linger_ms: 5,
            buffer_memory: 32 * 1024 * 1024,
            max_block_ms: 60 * 1000,
            acks: -1, // "all"
            retries: i32::MAX,
            delivery_timeout_ms: 120 * 1000,
            request_timeout_ms: 30 * 1000,
            enable_idempotence: true,
            max_request_size: 1024 * 1024,
            max_in_flight_requests_per_connection: 5,
            compression_type: CompressionType::None,
            connections_max_idle_ms: 9 * 60 * 1000,
            reconnect_backoff_ms: 50,
            reconnect_backoff_max_ms: 1000,
            retry_backoff_ms: 100,
            retry_backoff_max_ms: 1000,
            send_buffer_bytes: 128 * 1024,
            receive_buffer_bytes: 32 * 1024,
            socket_connection_setup_timeout_ms: 10_000,
            socket_connection_setup_timeout_max_ms: 30_000,
            metadata_max_age_ms: 5 * 60 * 1000,
            metadata_max_idle_ms: 5 * 60 * 1000,
            partitioner_adaptive_partitioning_enable: true,
            partitioner_availability_timeout_ms: 0,
            partitioner_ignore_keys: false,
            transactional_id: None,
            transaction_timeout_ms: 60_000,
            two_phase_commit_enable: false,
            explicitly_set: HashSet::new(),
        }
    }
}

impl ProducerConfig {
    /// Creates a new `ProducerConfig` with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Maximum number of in-flight requests per connection when idempotence is enabled.
    pub const MAX_IN_FLIGHT_REQUESTS_FOR_IDEMPOTENCE: i32 = MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION_FOR_IDEMPOTENCE;

    // --- Config key constants (matching Java string keys) ---

    /// Config key: `bootstrap.servers`
    pub const BOOTSTRAP_SERVERS_CONFIG: &'static str = "bootstrap.servers";
    /// Config key: `client.id`
    pub const CLIENT_ID_CONFIG: &'static str = "client.id";
    /// Config key: `batch.size`
    pub const BATCH_SIZE_CONFIG: &'static str = "batch.size";
    /// Config key: `linger.ms`
    pub const LINGER_MS_CONFIG: &'static str = "linger.ms";
    /// Config key: `buffer.memory`
    pub const BUFFER_MEMORY_CONFIG: &'static str = "buffer.memory";
    /// Config key: `max.block.ms`
    pub const MAX_BLOCK_MS_CONFIG: &'static str = "max.block.ms";
    /// Config key: `acks`
    pub const ACKS_CONFIG: &'static str = "acks";
    /// Config key: `retries`
    pub const RETRIES_CONFIG: &'static str = "retries";
    /// Config key: `delivery.timeout.ms`
    pub const DELIVERY_TIMEOUT_MS_CONFIG: &'static str = "delivery.timeout.ms";
    /// Config key: `request.timeout.ms`
    pub const REQUEST_TIMEOUT_MS_CONFIG: &'static str = "request.timeout.ms";
    /// Config key: `enable.idempotence`
    pub const ENABLE_IDEMPOTENCE_CONFIG: &'static str = "enable.idempotence";
    /// Config key: `max.request.size`
    pub const MAX_REQUEST_SIZE_CONFIG: &'static str = "max.request.size";
    /// Config key: `max.in.flight.requests.per.connection`
    pub const MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION: &'static str = "max.in.flight.requests.per.connection";
    /// Config key: `compression.type`
    pub const COMPRESSION_TYPE_CONFIG: &'static str = "compression.type";
    /// Config key: `connections.max.idle.ms`
    pub const CONNECTIONS_MAX_IDLE_MS_CONFIG: &'static str = "connections.max.idle.ms";
    /// Config key: `reconnect.backoff.ms`
    pub const RECONNECT_BACKOFF_MS_CONFIG: &'static str = "reconnect.backoff.ms";
    /// Config key: `reconnect.backoff.max.ms`
    pub const RECONNECT_BACKOFF_MAX_MS_CONFIG: &'static str = "reconnect.backoff.max.ms";
    /// Config key: `retry.backoff.ms`
    pub const RETRY_BACKOFF_MS_CONFIG: &'static str = "retry.backoff.ms";
    /// Config key: `retry.backoff.max.ms`
    pub const RETRY_BACKOFF_MAX_MS_CONFIG: &'static str = "retry.backoff.max.ms";
    /// Config key: `send.buffer.bytes`
    pub const SEND_BUFFER_CONFIG: &'static str = "send.buffer.bytes";
    /// Config key: `receive.buffer.bytes`
    pub const RECEIVE_BUFFER_CONFIG: &'static str = "receive.buffer.bytes";
    /// Config key: `metadata.max.age.ms`
    pub const METADATA_MAX_AGE_CONFIG: &'static str = "metadata.max.age.ms";
    /// Config key: `metadata.max.idle.ms`
    pub const METADATA_MAX_IDLE_CONFIG: &'static str = "metadata.max.idle.ms";
    /// Config key: `partitioner.adaptive.partitioning.enable`
    pub const PARTITIONER_ADAPTIVE_PARTITIONING_ENABLE_CONFIG: &'static str =
        "partitioner.adaptive.partitioning.enable";
    /// Config key: `partitioner.availability.timeout.ms`
    pub const PARTITIONER_AVAILABILITY_TIMEOUT_MS_CONFIG: &'static str = "partitioner.availability.timeout.ms";
    /// Config key: `partitioner.ignore.keys`
    pub const PARTITIONER_IGNORE_KEYS_CONFIG: &'static str = "partitioner.ignore.keys";
    /// Config key: `transactional.id`
    pub const TRANSACTIONAL_ID_CONFIG: &'static str = "transactional.id";
    /// Config key: `transaction.timeout.ms`
    pub const TRANSACTION_TIMEOUT_CONFIG: &'static str = "transaction.timeout.ms";
    /// Config key: `transaction.two.phase.commit.enable`
    pub const TRANSACTION_TWO_PHASE_COMMIT_ENABLE_CONFIG: &'static str = "transaction.two.phase.commit.enable";
    /// Config key: `security.protocol`
    pub const SECURITY_PROTOCOL_CONFIG: &'static str = common_client_configs::SECURITY_PROTOCOL_CONFIG;
    /// Config key: `sasl.mechanism`
    pub const SASL_MECHANISM_CONFIG: &'static str = sasl_configs::SASL_MECHANISM;
    /// Config key: `sasl.jaas.config`
    pub const SASL_JAAS_CONFIG: &'static str = sasl_configs::SASL_JAAS_CONFIG;

    /// Creates a `ProducerConfig` from a map of string key-value pairs.
    ///
    /// This is the Rust equivalent of Java's `new ProducerConfig(Map<String, Object>)`
    /// or `new ProducerConfig(Properties)`. Starts with default values and overrides
    /// each field that has a matching entry in the map.
    ///
    /// Unknown keys are logged as warnings and ignored, matching Java's behavior.
    ///
    /// # Errors
    ///
    /// Returns [`Error::IllegalArgument`] if a value cannot be parsed for its
    /// expected type (e.g., `"abc"` for an integer field).
    pub fn from_properties(props: &HashMap<String, String>) -> Result<Self, Error> {
        let mut config = Self { explicitly_set: props.keys().cloned().collect(), ..Default::default() };

        for (key, value) in props {
            match key.as_str() {
                Self::BOOTSTRAP_SERVERS_CONFIG => {
                    config.bootstrap_servers = value.split(',').map(|s| s.trim().to_string()).collect();
                },
                Self::CLIENT_ID_CONFIG => {
                    config.client_id = value.to_string();
                },
                Self::BATCH_SIZE_CONFIG => {
                    config.batch_size = Self::parse_i32(key, value)?;
                },
                Self::LINGER_MS_CONFIG => {
                    config.linger_ms = Self::parse_i64(key, value)?;
                },
                Self::BUFFER_MEMORY_CONFIG => {
                    config.buffer_memory = Self::parse_i64(key, value)?;
                },
                Self::MAX_BLOCK_MS_CONFIG => {
                    config.max_block_ms = Self::parse_i64(key, value)?;
                },
                Self::ACKS_CONFIG => {
                    config.acks = Self::parse_acks(value)?;
                },
                Self::RETRIES_CONFIG => {
                    config.retries = Self::parse_i32(key, value)?;
                },
                Self::DELIVERY_TIMEOUT_MS_CONFIG => {
                    config.delivery_timeout_ms = Self::parse_i32(key, value)?;
                },
                Self::REQUEST_TIMEOUT_MS_CONFIG => {
                    config.request_timeout_ms = Self::parse_i32(key, value)?;
                },
                Self::ENABLE_IDEMPOTENCE_CONFIG => {
                    config.enable_idempotence = Self::parse_bool(key, value)?;
                },
                Self::MAX_REQUEST_SIZE_CONFIG => {
                    config.max_request_size = Self::parse_i32(key, value)?;
                },
                Self::MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION => {
                    config.max_in_flight_requests_per_connection = Self::parse_i32(key, value)?;
                },
                Self::COMPRESSION_TYPE_CONFIG => {
                    config.compression_type = CompressionType::for_name(value)?;
                },
                Self::CONNECTIONS_MAX_IDLE_MS_CONFIG => {
                    config.connections_max_idle_ms = Self::parse_i64(key, value)?;
                },
                Self::RECONNECT_BACKOFF_MS_CONFIG => {
                    config.reconnect_backoff_ms = Self::parse_i64(key, value)?;
                },
                Self::RECONNECT_BACKOFF_MAX_MS_CONFIG => {
                    config.reconnect_backoff_max_ms = Self::parse_i64(key, value)?;
                },
                Self::RETRY_BACKOFF_MS_CONFIG => {
                    config.retry_backoff_ms = Self::parse_i64(key, value)?;
                },
                Self::RETRY_BACKOFF_MAX_MS_CONFIG => {
                    config.retry_backoff_max_ms = Self::parse_i64(key, value)?;
                },
                Self::SEND_BUFFER_CONFIG => {
                    config.send_buffer_bytes = Self::parse_i32(key, value)?;
                },
                Self::RECEIVE_BUFFER_CONFIG => {
                    config.receive_buffer_bytes = Self::parse_i32(key, value)?;
                },
                Self::METADATA_MAX_AGE_CONFIG => {
                    config.metadata_max_age_ms = Self::parse_i64(key, value)?;
                },
                Self::METADATA_MAX_IDLE_CONFIG => {
                    config.metadata_max_idle_ms = Self::parse_i64(key, value)?;
                },
                Self::PARTITIONER_ADAPTIVE_PARTITIONING_ENABLE_CONFIG => {
                    config.partitioner_adaptive_partitioning_enable = Self::parse_bool(key, value)?;
                },
                Self::PARTITIONER_AVAILABILITY_TIMEOUT_MS_CONFIG => {
                    config.partitioner_availability_timeout_ms = Self::parse_i64(key, value)?;
                },
                Self::PARTITIONER_IGNORE_KEYS_CONFIG => {
                    config.partitioner_ignore_keys = Self::parse_bool(key, value)?;
                },
                Self::TRANSACTIONAL_ID_CONFIG => {
                    config.transactional_id = if value.is_empty() {
                        None
                    } else {
                        Some(value.to_string())
                    };
                },
                Self::TRANSACTION_TIMEOUT_CONFIG => {
                    config.transaction_timeout_ms = Self::parse_i32(key, value)?;
                },
                Self::TRANSACTION_TWO_PHASE_COMMIT_ENABLE_CONFIG => {
                    config.two_phase_commit_enable = Self::parse_bool(key, value)?;
                },
                Self::SECURITY_PROTOCOL_CONFIG => {
                    config.security_protocol = SecurityProtocol::for_name(value).ok_or_else(|| {
                        Error::config_value_message(
                            key,
                            value,
                            format!("Valid values are: {:?}", SecurityProtocol::names()),
                        )
                    })?;
                },
                Self::SASL_MECHANISM_CONFIG => {
                    config.sasl_config.mechanism = value.to_string();
                },
                Self::SASL_JAAS_CONFIG => {
                    config.sasl_config.jaas_config = if value.is_empty() {
                        None
                    } else {
                        Some(value.to_string())
                    };
                },
                key if key.starts_with("ssl.") => {
                    ssl_configs::apply_ssl_config_key(&mut config.ssl_config, key, value);
                },
                _ => {
                    warn!("Unknown producer configuration key: {}", key);
                },
            }
        }

        // Order matters and matches Java's constructor: idempotence validation
        // may override `enable.idempotence`, and the client id derivation reads
        // `transactional.id`.
        config.post_process_and_validate_idempotence_configs()?;
        config.maybe_override_client_id();

        Ok(config)
    }

    /// Whether the user set `key` explicitly.
    ///
    /// Replaces Java's `this.originals().containsKey(key)`.
    fn user_configured(&self, key: &str) -> bool {
        self.explicitly_set.contains(key)
    }

    /// Validates and post-processes the idempotence-dependent configs.
    ///
    /// Translated from Java's `postProcessAndValidateIdempotenceConfigs`.
    ///
    /// Java's asymmetry is deliberate and preserved: for `retries` and `acks`,
    /// an incompatible value **silently disables** idempotence unless the user
    /// asked for idempotence explicitly, in which case it is an error. For
    /// `max.in.flight.requests.per.connection` it is **always** an error. The
    /// silent-disable path is what keeps existing non-idempotent configurations
    /// working, so removing it would be a breaking change.
    fn post_process_and_validate_idempotence_configs(&mut self) -> Result<(), Error> {
        let user_configured_idempotence = self.user_configured(Self::ENABLE_IDEMPOTENCE_CONFIG);
        let mut idempotence_enabled = self.enable_idempotence;
        let mut should_disable_idempotence = false;

        if idempotence_enabled {
            if self.retries == 0 {
                if user_configured_idempotence {
                    return Err(Error::config(format!(
                        "Must set {} to non-zero when using the idempotent producer.",
                        Self::RETRIES_CONFIG
                    )));
                }
                info!("Idempotence will be disabled because {} is set to 0.", Self::RETRIES_CONFIG);
                should_disable_idempotence = true;
            }

            if self.acks != -1 {
                if user_configured_idempotence {
                    return Err(Error::config(format!(
                        "Must set {} to all in order to use the idempotent producer. Otherwise we cannot guarantee idempotence.",
                        Self::ACKS_CONFIG
                    )));
                }
                info!(
                    "Idempotence will be disabled because {} is set to {}, not set to 'all'.",
                    Self::ACKS_CONFIG,
                    self.acks
                );
                should_disable_idempotence = true;
            }

            // Unlike the two above, this is always an error — never a silent
            // disable — regardless of whether the user asked for idempotence.
            if Self::MAX_IN_FLIGHT_REQUESTS_FOR_IDEMPOTENCE < self.max_in_flight_requests_per_connection {
                return Err(Error::config(format!(
                    "To use the idempotent producer, {} must be set to at most 5. Current value is {}.",
                    Self::MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION,
                    self.max_in_flight_requests_per_connection
                )));
            }
        }

        if should_disable_idempotence {
            self.enable_idempotence = false;
            idempotence_enabled = false;
        }

        // Validated after the idempotence-dependent configs because
        // `enable.idempotence` may have just been overridden above.
        if !idempotence_enabled && self.user_configured(Self::TRANSACTIONAL_ID_CONFIG) {
            return Err(Error::config(format!(
                "Cannot set a {} without also enabling idempotence.",
                Self::TRANSACTIONAL_ID_CONFIG
            )));
        }

        // In standard Kafka transactions the broker enforces
        // `transaction.timeout.ms` and aborts any transaction not completed in
        // time. With two-phase commit an external coordinator decides when to
        // finalize, so broker-side timeouts do not apply. Disallow using both.
        if self.two_phase_commit_enable && self.user_configured(Self::TRANSACTION_TIMEOUT_CONFIG) {
            return Err(Error::config(format!(
                "Cannot set {} when {} is set to true. Transactions will not expire with two-phase commit enabled.",
                Self::TRANSACTION_TIMEOUT_CONFIG,
                Self::TRANSACTION_TWO_PHASE_COMMIT_ENABLE_CONFIG
            )));
        }

        Ok(())
    }

    /// Derives `client.id` when the user did not set one.
    ///
    /// Translated from Java's `maybeOverrideClientId`. The derived form is
    /// `producer-<transactional.id>` when a transactional id is set, otherwise
    /// `producer-<n>` from a process-wide counter starting at 1 — matching
    /// Java's `static AtomicInteger PRODUCER_CLIENT_ID_SEQUENCE`.
    fn maybe_override_client_id(&mut self) {
        if self.user_configured(Self::CLIENT_ID_CONFIG) {
            return;
        }
        self.client_id = match &self.transactional_id {
            Some(transactional_id) => format!("producer-{transactional_id}"),
            None => format!(
                "producer-{}",
                PRODUCER_CLIENT_ID_SEQUENCE.fetch_add(1, atomic::Ordering::Relaxed)
            ),
        };
    }

    /// Parses a string value as `i32`.
    fn parse_i32(key: &str, value: &str) -> Result<i32, Error> {
        value.trim().parse::<i32>().map_err(|_| Error::config_value(key, value))
    }

    /// Parses a string value as `i64`.
    fn parse_i64(key: &str, value: &str) -> Result<i64, Error> {
        value.trim().parse::<i64>().map_err(|_| Error::config_value(key, value))
    }

    /// Parses a string value as `bool`.
    fn parse_bool(key: &str, value: &str) -> Result<bool, Error> {
        match value.trim() {
            "true" => Ok(true),
            "false" => Ok(false),
            _ => Err(Error::config_value(key, value)),
        }
    }

    /// Parses the acks string, converting "all" to -1.
    ///
    /// Java's `parseAcks` catches `NumberFormatException` and throws
    /// `ConfigException` (`ProducerConfig.java:653-659`). `ConfigException extends
    /// KafkaException`, so the error must stay inside the `KafkaException`
    /// hierarchy: returning a `String` here erased the class at the boundary and
    /// left the caller free to pick the wrong one.
    pub fn parse_acks(acks_string: &str) -> Result<i16, Error> {
        let trimmed = acks_string.trim();
        if trimmed.eq_ignore_ascii_case("all") {
            Ok(-1)
        } else {
            trimmed
                .parse::<i16>()
                .map_err(|_| Error::config(format!("Invalid configuration value for 'acks': {acks_string}")))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_values() {
        let config = ProducerConfig::default();
        assert_eq!(config.batch_size, 16384);
        assert_eq!(config.linger_ms, 5);
        assert_eq!(config.buffer_memory, 32 * 1024 * 1024);
        assert_eq!(config.max_block_ms, 60_000);
        assert_eq!(config.acks, -1);
        assert_eq!(config.retries, i32::MAX);
        assert_eq!(config.delivery_timeout_ms, 120_000);
        assert_eq!(config.request_timeout_ms, 30_000);
        assert!(config.enable_idempotence);
        assert_eq!(config.max_request_size, 1_048_576);
        assert_eq!(config.max_in_flight_requests_per_connection, 5);
        assert_eq!(config.compression_type, CompressionType::None);
        assert_eq!(config.connections_max_idle_ms, 540_000);
        assert_eq!(config.reconnect_backoff_ms, 50);
        assert_eq!(config.reconnect_backoff_max_ms, 1000);
        assert_eq!(config.retry_backoff_ms, 100);
        assert_eq!(config.retry_backoff_max_ms, 1000);
        assert_eq!(config.send_buffer_bytes, 131_072);
        assert_eq!(config.receive_buffer_bytes, 32_768);
        assert_eq!(config.metadata_max_age_ms, 300_000);
        assert_eq!(config.metadata_max_idle_ms, 300_000);
        assert!(config.partitioner_adaptive_partitioning_enable);
        assert_eq!(config.partitioner_availability_timeout_ms, 0);
        assert!(!config.partitioner_ignore_keys);
        assert!(config.transactional_id.is_none());
        assert_eq!(config.transaction_timeout_ms, 60_000);
    }

    #[test]
    fn test_from_properties_basic() {
        let mut props = HashMap::new();
        props.insert("bootstrap.servers".to_string(), "host1:9092,host2:9093".to_string());
        props.insert("client.id".to_string(), "my-producer".to_string());
        props.insert("batch.size".to_string(), "32768".to_string());
        props.insert("linger.ms".to_string(), "10".to_string());
        props.insert("acks".to_string(), "all".to_string());
        props.insert("compression.type".to_string(), "gzip".to_string());
        props.insert("enable.idempotence".to_string(), "false".to_string());

        let config = ProducerConfig::from_properties(&props).unwrap();
        assert_eq!(config.bootstrap_servers, vec!["host1:9092", "host2:9093"]);
        assert_eq!(config.client_id, "my-producer");
        assert_eq!(config.batch_size, 32768);
        assert_eq!(config.linger_ms, 10);
        assert_eq!(config.acks, -1);
        assert_eq!(config.compression_type, CompressionType::Gzip);
        assert!(!config.enable_idempotence);
    }

    #[test]
    fn test_from_properties_defaults_for_missing() {
        let props = HashMap::new();
        let config = ProducerConfig::from_properties(&props).unwrap();
        // All fields should have default values
        assert_eq!(config.batch_size, 16384);
        assert_eq!(config.linger_ms, 5);
        assert_eq!(config.acks, -1);
    }

    #[test]
    fn test_from_properties_invalid_value() {
        let mut props = HashMap::new();
        props.insert("batch.size".to_string(), "not-a-number".to_string());
        let result = ProducerConfig::from_properties(&props);
        assert!(result.is_err());
    }

    #[test]
    fn test_from_properties_unknown_key_ignored() {
        let mut props = HashMap::new();
        props.insert("unknown.key".to_string(), "value".to_string());
        props.insert("bootstrap.servers".to_string(), "localhost:9092".to_string());
        let config = ProducerConfig::from_properties(&props).unwrap();
        assert_eq!(config.bootstrap_servers, vec!["localhost:9092"]);
    }

    #[test]
    fn test_from_properties_transactional_id() {
        let mut props = HashMap::new();
        props.insert("transactional.id".to_string(), "my-txn".to_string());
        let config = ProducerConfig::from_properties(&props).unwrap();
        assert_eq!(config.transactional_id, Some("my-txn".to_string()));

        // Empty string -> None
        let mut props = HashMap::new();
        props.insert("transactional.id".to_string(), String::new());
        let config = ProducerConfig::from_properties(&props).unwrap();
        assert_eq!(config.transactional_id, None);
    }

    #[test]
    fn test_parse_acks() {
        assert_eq!(ProducerConfig::parse_acks("all").unwrap(), -1);
        assert_eq!(ProducerConfig::parse_acks("ALL").unwrap(), -1);
        assert_eq!(ProducerConfig::parse_acks("-1").unwrap(), -1);
        assert_eq!(ProducerConfig::parse_acks("0").unwrap(), 0);
        assert_eq!(ProducerConfig::parse_acks("1").unwrap(), 1);

        // Java's `parseAcks` catches `NumberFormatException` and throws
        // `ConfigException` (`ProducerConfig.java:653-659`), so the class matters
        // as much as the message: `ConfigException extends KafkaException`, and a
        // caller validating a config map with `is_kafka_error()` must see it.
        let error = ProducerConfig::parse_acks("invalid").expect_err("a non-numeric acks is a config error");
        assert!(matches!(error, Error::Config(_)), "expected Error::Config, got {error:?}");
        assert_eq!(error.message(), "Invalid configuration value for 'acks': invalid");
        assert!(error.is_kafka_error());
    }

    /// Every `ConfigException` this config raises must answer `true` to
    /// `is_kafka_error()`, matching `ConfigException extends KafkaException`.
    ///
    /// The six sites are Java's `parseAcks` (`ProducerConfig.java:657`) and the
    /// five throws in `postProcessAndValidateIdempotenceConfigs` (`:603`, `:612`,
    /// `:621`, `:635`, `:645`). They all used to be `IllegalArgumentException`,
    /// which sits *beside* `KafkaException` rather than below it, so
    /// `is_kafka_error()` answered `false` and a bad `acks` slipped past a caller
    /// that a bad `linger.ms` did not.
    #[test]
    fn config_errors_are_inside_the_kafka_error_hierarchy() {
        let cases: [(&[(&str, &str)], &str); 6] = [
            (
                &[("acks", "not-a-number")],
                "Invalid configuration value for 'acks': not-a-number",
            ),
            (
                &[("enable.idempotence", "true"), ("retries", "0")],
                "Must set retries to non-zero when using the idempotent producer.",
            ),
            (
                &[("enable.idempotence", "true"), ("acks", "1")],
                "Must set acks to all in order to use the idempotent producer. Otherwise we cannot guarantee idempotence.",
            ),
            (
                &[
                    ("enable.idempotence", "true"),
                    ("max.in.flight.requests.per.connection", "6"),
                ],
                "To use the idempotent producer, max.in.flight.requests.per.connection must be set to at most 5. \
                 Current value is 6.",
            ),
            (
                &[("enable.idempotence", "false"), ("transactional.id", "txn-id")],
                "Cannot set a transactional.id without also enabling idempotence.",
            ),
            (
                &[
                    ("transactional.id", "txn-id"),
                    ("transaction.two.phase.commit.enable", "true"),
                    ("transaction.timeout.ms", "1000"),
                ],
                "Cannot set transaction.timeout.ms when transaction.two.phase.commit.enable is set to true. \
                 Transactions will not expire with two-phase commit enabled.",
            ),
        ];

        for (props, expected_message) in cases {
            let error = ProducerConfig::from_properties(&props_with(props)).expect_err("expected a config error");
            assert_eq!(error.message(), expected_message, "for {props:?}");
            assert!(
                matches!(error, Error::Config(_)),
                "for {props:?}: expected Error::Config, got {error:?}"
            );
            assert!(error.is_kafka_error(), "for {props:?}: a config error is a Kafka error");
        }
    }

    /// Translated from `ProducerConfigTest.testInvalidSecurityProtocol`.
    #[test]
    fn test_invalid_security_protocol() {
        let mut props = HashMap::new();
        props.insert("security.protocol".to_string(), "abc".to_string());
        props.insert("bootstrap.servers".to_string(), "localhost:9092".to_string());
        let err = ProducerConfig::from_properties(&props).unwrap_err();
        let msg = format!("{}", err);
        assert!(
            msg.contains("security.protocol"),
            "Error message should contain config key, got: {}",
            msg
        );
    }

    /// Translated from `ProducerConfigTest.testCaseInsensitiveSecurityProtocol`.
    #[test]
    fn test_case_insensitive_security_protocol() {
        let mut props = HashMap::new();
        props.insert("security.protocol".to_string(), "sasl_ssl".to_string());
        props.insert("bootstrap.servers".to_string(), "localhost:9092".to_string());
        let config = ProducerConfig::from_properties(&props).unwrap();
        assert_eq!(config.security_protocol, SecurityProtocol::SaslSsl);
    }

    #[test]
    fn test_sasl_config_from_properties() {
        let mut props = HashMap::new();
        props.insert("sasl.mechanism".to_string(), "PLAIN".to_string());
        props.insert(
            "sasl.jaas.config".to_string(),
            "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"alice\" password=\"secret\";"
                .to_string(),
        );
        props.insert("bootstrap.servers".to_string(), "localhost:9092".to_string());
        let config = ProducerConfig::from_properties(&props).unwrap();
        assert_eq!(config.sasl_config.mechanism, "PLAIN");
        assert_eq!(config.sasl_config.resolve_username(), Some("alice"));
        assert_eq!(config.sasl_config.resolve_password(), Some("secret"));
    }

    #[test]
    fn test_ssl_config_from_properties() {
        let mut props = HashMap::new();
        props.insert("ssl.truststore.location".to_string(), "/path/to/truststore.pem".to_string());
        props.insert("ssl.keystore.location".to_string(), "/path/to/keystore.pem".to_string());
        props.insert("ssl.endpoint.identification.algorithm".to_string(), String::new());
        props.insert("bootstrap.servers".to_string(), "localhost:9092".to_string());
        let config = ProducerConfig::from_properties(&props).unwrap();
        assert_eq!(
            config.ssl_config.truststore_location.as_deref(),
            Some("/path/to/truststore.pem")
        );
        assert_eq!(config.ssl_config.keystore_location.as_deref(), Some("/path/to/keystore.pem"));
        assert_eq!(config.ssl_config.endpoint_identification_algorithm, "");
    }

    // -- Idempotence config validation --------------------------------------
    //
    // Translated from `ProducerConfigTest` and the four pure-config tests in
    // `KafkaProducerTest`. The latter construct a `ProducerConfig` from
    // `Properties` and assert on values without creating a producer or touching
    // the network, so they belong here rather than in a producer test.

    /// Java's `KafkaProducerTest.baseProperties()`.
    fn base_properties() -> HashMap<String, String> {
        HashMap::from([("bootstrap.servers".to_string(), "localhost:9999".to_string())])
    }

    fn props_with(extra: &[(&str, &str)]) -> HashMap<String, String> {
        let mut props = base_properties();
        for (key, value) in extra {
            props.insert((*key).to_string(), (*value).to_string());
        }
        props
    }

    /// Translated from `KafkaProducerTest.testOverwriteAcksAndRetriesForIdempotentProducers`.
    #[test]
    fn test_overwrite_acks_and_retries_for_idempotent_producers() {
        let props = props_with(&[("transactional.id", "transactionalId")]);
        let config = ProducerConfig::from_properties(&props).expect("config should be valid");

        assert!(config.enable_idempotence);
        assert_eq!(config.acks, -1);
        assert_eq!(config.retries, i32::MAX);
        // The derived client id form Java asserts on.
        assert_eq!(config.client_id, "producer-transactionalId");
    }

    /// Translated from `KafkaProducerTest.testAcksAndIdempotenceForIdempotentProducers`.
    #[test]
    fn test_acks_and_idempotence_for_idempotent_producers() {
        // Valid: acks=0 with idempotence explicitly off.
        let config = ProducerConfig::from_properties(&props_with(&[("acks", "0"), ("enable.idempotence", "false")]))
            .expect("valid");
        assert!(!config.enable_idempotence, "idempotence should be overwritten");
        assert_eq!(config.acks, 0, "acks should be overwritten");

        // Valid: transactional.id alone leaves the idempotence/acks defaults.
        let config =
            ProducerConfig::from_properties(&props_with(&[("transactional.id", "transactionalId")])).expect("valid");
        assert!(config.enable_idempotence, "idempotence should be set with the default value");
        assert_eq!(config.acks, -1, "acks should be set with the default value");

        // Valid: acks=all with idempotence explicitly off.
        let config = ProducerConfig::from_properties(&props_with(&[("acks", "all"), ("enable.idempotence", "false")]))
            .expect("valid");
        assert!(!config.enable_idempotence, "idempotence should be overwritten");
        assert_eq!(config.acks, -1, "acks should be overwritten");

        // Valid: acks=0 with idempotence UNSET silently disables idempotence.
        // This is the path that keeps existing configurations working.
        let config = ProducerConfig::from_properties(&props_with(&[("acks", "0")])).expect("valid");
        assert!(
            !config.enable_idempotence,
            "idempotence should be disabled when acks not set to all and `enable.idempotence` is unset"
        );
        assert_eq!(config.acks, 0, "acks should be set with overridden value");

        // Same for acks=1.
        let config = ProducerConfig::from_properties(&props_with(&[("acks", "1")])).expect("valid");
        assert!(!config.enable_idempotence);
        assert_eq!(config.acks, 1);

        // Invalid: transactional.id without idempotence.
        let error = ProducerConfig::from_properties(&props_with(&[
            ("acks", "0"),
            ("enable.idempotence", "false"),
            ("transactional.id", "transactionalId"),
        ]))
        .expect_err("transactional.id requires idempotence");
        assert_eq!(
            error.message(),
            "Cannot set a transactional.id without also enabling idempotence."
        );

        // Invalid: explicitly enabling idempotence with acks=1 still errors,
        // rather than silently disabling.
        let error = ProducerConfig::from_properties(&props_with(&[("acks", "1"), ("enable.idempotence", "true")]))
            .expect_err("explicit idempotence with acks!=all must error");
        assert_eq!(
            error.message(),
            "Must set acks to all in order to use the idempotent producer. Otherwise we cannot guarantee idempotence."
        );

        // Invalid: acks=0 with a transactional id — idempotence is silently
        // disabled by the acks arm, and the transactional.id check then fails.
        let error =
            ProducerConfig::from_properties(&props_with(&[("acks", "0"), ("transactional.id", "transactionalId")]))
                .expect_err("transactional producer requires acks=all");
        assert_eq!(
            error.message(),
            "Cannot set a transactional.id without also enabling idempotence."
        );
    }

    /// Translated from `KafkaProducerTest.testRetriesAndIdempotenceForIdempotentProducers`.
    #[test]
    fn test_retries_and_idempotence_for_idempotent_producers() {
        // Valid: retries=0 with idempotence explicitly off.
        let config = ProducerConfig::from_properties(&props_with(&[("retries", "0"), ("enable.idempotence", "false")]))
            .expect("valid");
        assert!(!config.enable_idempotence, "idempotence should be overwritten");
        assert_eq!(config.retries, 0, "retries should be overwritten");

        // Valid: retries=0 with idempotence UNSET silently disables idempotence.
        let config = ProducerConfig::from_properties(&props_with(&[("retries", "0")])).expect("valid");
        assert!(
            !config.enable_idempotence,
            "idempotence should be disabled when retries set to 0 and `enable.idempotence` is unset"
        );
        assert_eq!(config.retries, 0, "retries should be set with overridden value");

        // Invalid: transactional.id without idempotence.
        let error = ProducerConfig::from_properties(&props_with(&[
            ("retries", "0"),
            ("enable.idempotence", "false"),
            ("transactional.id", "transactionalId"),
        ]))
        .expect_err("transactional.id requires idempotence");
        assert_eq!(
            error.message(),
            "Cannot set a transactional.id without also enabling idempotence."
        );

        // Invalid: explicitly enabling idempotence with retries=0.
        let error = ProducerConfig::from_properties(&props_with(&[("retries", "0"), ("enable.idempotence", "true")]))
            .expect_err("explicit idempotence with retries=0 must error");
        assert_eq!(
            error.message(),
            "Must set retries to non-zero when using the idempotent producer."
        );

        // Invalid: retries=0 with a transactional id.
        let error =
            ProducerConfig::from_properties(&props_with(&[("retries", "0"), ("transactional.id", "transactionalId")]))
                .expect_err("transactional producer requires non-zero retries");
        assert_eq!(
            error.message(),
            "Cannot set a transactional.id without also enabling idempotence."
        );
    }

    /// Translated from `KafkaProducerTest.testInflightRequestsAndIdempotenceForIdempotentProducers`.
    #[test]
    fn test_inflight_requests_and_idempotence_for_idempotent_producers() {
        // Valid: in-flight above the cap is fine when idempotence is off.
        let config = ProducerConfig::from_properties(&props_with(&[
            ("max.in.flight.requests.per.connection", "6"),
            ("enable.idempotence", "false"),
        ]))
        .expect("valid");
        assert!(!config.enable_idempotence, "idempotence should be overwritten");
        assert_eq!(config.max_in_flight_requests_per_connection, 6);

        // Invalid: with idempotence on (by default), exceeding the cap is ALWAYS
        // an error — this arm never silently disables, unlike acks and retries.
        let error = ProducerConfig::from_properties(&props_with(&[("max.in.flight.requests.per.connection", "6")]))
            .expect_err("in-flight above 5 must error");
        assert_eq!(
            error.message(),
            "To use the idempotent producer, max.in.flight.requests.per.connection must be set to at most 5. Current value is 6."
        );

        // Invalid: exactly at the cap, idempotence explicitly off, transactional
        // id set. Pins that the in-flight arm does not mask the transactional-id
        // arm — the in-flight value is legal here, so the error must come from
        // the transactional-id check.
        let error = ProducerConfig::from_properties(&props_with(&[
            ("max.in.flight.requests.per.connection", "5"),
            ("enable.idempotence", "false"),
            ("transactional.id", "transactionalId"),
        ]))
        .expect_err("transactional.id without idempotence must error even at the in-flight cap");
        assert_eq!(
            error.message(),
            "Cannot set a transactional.id without also enabling idempotence."
        );

        // Invalid: above the cap with idempotence explicitly on. Pins that the
        // in-flight arm fires regardless of how idempotence came to be enabled.
        let error = ProducerConfig::from_properties(&props_with(&[
            ("max.in.flight.requests.per.connection", "6"),
            ("enable.idempotence", "true"),
        ]))
        .expect_err("explicit idempotence above the cap must error");
        assert_eq!(
            error.message(),
            "To use the idempotent producer, max.in.flight.requests.per.connection must be set to at most 5. Current value is 6."
        );

        // Invalid: above the cap with a transactional id. Pins that the in-flight
        // arm fires ahead of the transactional-id arm.
        let error = ProducerConfig::from_properties(&props_with(&[
            ("max.in.flight.requests.per.connection", "6"),
            ("transactional.id", "transactionalId"),
        ]))
        .expect_err("transactional producer above the cap must error");
        assert_eq!(
            error.message(),
            "To use the idempotent producer, max.in.flight.requests.per.connection must be set to at most 5. Current value is 6."
        );
    }

    /// Translated from `ProducerConfigTest.testUpperboundCheckOfEnableIdempotence`.
    #[test]
    fn test_upperbound_check_of_enable_idempotence() {
        let error = ProducerConfig::from_properties(&props_with(&[("max.in.flight.requests.per.connection", "6")]))
            .expect_err("6 exceeds the cap");
        assert_eq!(
            error.message(),
            "To use the idempotent producer, max.in.flight.requests.per.connection must be set to at most 5. Current value is 6."
        );

        // Exactly at the cap is allowed.
        ProducerConfig::from_properties(&props_with(&[("max.in.flight.requests.per.connection", "5")]))
            .expect("5 is at the cap and must be accepted");
    }

    /// Translated from `ProducerConfigTest.testTwoPhaseCommitIncompatibleWithTransactionTimeout`.
    #[test]
    fn test_two_phase_commit_incompatible_with_transaction_timeout() {
        let both = props_with(&[
            ("enable.idempotence", "true"),
            ("transactional.id", "test-txn-id"),
            ("transaction.two.phase.commit.enable", "true"),
            ("transaction.timeout.ms", "60000"),
        ]);
        let error = ProducerConfig::from_properties(&both).expect_err("2PC and timeout conflict");
        assert!(error.message().contains(ProducerConfig::TRANSACTION_TIMEOUT_CONFIG));
        assert!(
            error
                .message()
                .contains(ProducerConfig::TRANSACTION_TWO_PHASE_COMMIT_ENABLE_CONFIG)
        );

        // Setting one but not the other is valid.
        let only_2pc = props_with(&[
            ("enable.idempotence", "true"),
            ("transactional.id", "test-txn-id"),
            ("transaction.two.phase.commit.enable", "true"),
        ]);
        ProducerConfig::from_properties(&only_2pc).expect("2PC alone is valid");

        let only_timeout = props_with(&[
            ("enable.idempotence", "true"),
            ("transactional.id", "test-txn-id"),
            ("transaction.two.phase.commit.enable", "false"),
            ("transaction.timeout.ms", "60000"),
        ]);
        ProducerConfig::from_properties(&only_timeout).expect("timeout alone is valid");
    }

    // -- client.id derivation ------------------------------------------------

    /// Java's `maybeOverrideClientId`: an explicit client.id is preserved.
    #[test]
    fn test_explicit_client_id_is_preserved() {
        let config = ProducerConfig::from_properties(&props_with(&[("client.id", "my-client")])).expect("valid");
        assert_eq!(config.client_id, "my-client");
    }

    /// Without an explicit client.id or transactional.id, the derived form is
    /// `producer-<n>` from the process-wide counter.
    #[test]
    fn test_client_id_derived_from_sequence() {
        let first = ProducerConfig::from_properties(&base_properties()).expect("valid");
        let second = ProducerConfig::from_properties(&base_properties()).expect("valid");

        assert!(
            first.client_id.starts_with("producer-"),
            "expected a derived client id, got {}",
            first.client_id
        );
        // The counter is process-wide, so successive configs differ. Compare
        // rather than asserting absolute values, since test order is arbitrary.
        assert_ne!(first.client_id, second.client_id);
        let n: i32 = first.client_id.trim_start_matches("producer-").parse().expect("numeric suffix");
        assert!(n >= 1, "Java's sequence starts at 1");
    }
}
