// Copyright 2025 Confluent Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Configuration for the Kafka Producer.
//!
//! Translated from `org.apache.kafka.clients.producer.ProducerConfig`.
//!
//! This is a Rust struct with named fields rather than the Java `ConfigDef`
//! reflection framework. The field names and default values match the Java
//! config keys.

use std::collections::HashMap;

use log::warn;

use crate::common::KafkaError;
use crate::common::config::sasl_configs;
use crate::common::config::ssl_configs;
use crate::common::config::{SaslConfig, SslConfig};
use crate::common::record::CompressionType;
use crate::common::security::SecurityProtocol;
use crate::common_client_configs;

/// Maximum number of in-flight requests per connection when idempotence is enabled.
/// Aligned with `ProducerStateEntry.NUM_BATCHES_TO_RETAIN` on the broker.
const MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION_FOR_IDEMPOTENCE: i32 = 5;

/// Configuration for the Kafka Producer.
///
/// Documentation for these configurations can be found in the
/// [Kafka documentation](http://kafka.apache.org/documentation.html#producerconfigs).
///
/// Corresponds to `org.apache.kafka.clients.producer.ProducerConfig`.
#[derive(Clone, Debug)]
pub struct ProducerConfig {
    // --- Connection ---
    /// `bootstrap.servers` - A list of host/port pairs to use for establishing the
    /// initial connection to the Kafka cluster.
    pub(crate) bootstrap_servers: Vec<String>,

    /// `client.id` - An id string to pass to the server when making requests.
    pub(crate) client_id: String,

    // --- Security ---
    /// `security.protocol` - Protocol used to communicate with brokers.
    /// Default: `SecurityProtocol::Plaintext`.
    pub(crate) security_protocol: SecurityProtocol,

    /// SASL configuration (mechanism, JAAS config, credentials).
    pub(crate) sasl_config: SaslConfig,

    /// SSL/TLS configuration.
    pub(crate) ssl_config: SslConfig,

    // --- Batching ---
    /// `batch.size` - The producer will attempt to batch records together into fewer
    /// requests whenever multiple records are being sent to the same partition.
    /// Default: 16384 bytes.
    pub(crate) batch_size: i32,

    /// `linger.ms` - Upper bound on the delay for batching.
    /// Default: 5 ms (changed from 0 in Apache Kafka 4.0).
    pub(crate) linger_ms: i64,

    // --- Buffering ---
    /// `buffer.memory` - Total bytes of memory the producer can use to buffer records
    /// waiting to be sent. Default: 32 MiB.
    pub(crate) buffer_memory: i64,

    /// `max.block.ms` - Maximum time `send()` and `partitionsFor()` will block.
    /// Default: 60000 ms.
    pub(crate) max_block_ms: i64,

    // --- Reliability ---
    /// `acks` - Number of acknowledgments the producer requires the leader to have
    /// received. Allowed values: 0, 1, -1 (all). Default: -1 (all).
    pub(crate) acks: i16,

    /// `retries` - Number of times to retry a request that fails with a transient error.
    /// Default: `i32::MAX` (effectively infinite retries bounded by delivery timeout).
    pub(crate) retries: i32,

    /// `delivery.timeout.ms` - Upper bound on time to report success or failure after
    /// `send()` returns. Default: 120000 ms.
    pub(crate) delivery_timeout_ms: i32,

    /// `request.timeout.ms` - Maximum time the client will wait for a response.
    /// Default: 30000 ms.
    pub(crate) request_timeout_ms: i32,

    /// `enable.idempotence` - When true, exactly-once delivery semantics are enabled.
    /// Default: true.
    pub(crate) enable_idempotence: bool,

    // --- Sizing ---
    /// `max.request.size` - Maximum size of a request in bytes.
    /// Default: 1048576 (1 MiB).
    pub(crate) max_request_size: i32,

    /// `max.in.flight.requests.per.connection` - Maximum number of unacknowledged
    /// requests per connection. Default: 5.
    pub(crate) max_in_flight_requests_per_connection: i32,

    // --- Compression ---
    /// `compression.type` - Compression type for all data generated by the producer.
    /// Default: `CompressionType::None`.
    pub(crate) compression_type: CompressionType,

    // --- Connections ---
    /// `connections.max.idle.ms` - Close idle connections after this duration.
    /// Default: 540000 ms (9 minutes).
    pub(crate) connections_max_idle_ms: i64,

    /// `reconnect.backoff.ms` - Base wait time before attempting to reconnect.
    /// Default: 50 ms.
    pub(crate) reconnect_backoff_ms: i64,

    /// `reconnect.backoff.max.ms` - Maximum wait time before reconnection attempts.
    /// Default: 1000 ms.
    pub(crate) reconnect_backoff_max_ms: i64,

    /// `retry.backoff.ms` - Wait time before retrying a failed request.
    /// Default: 100 ms.
    pub(crate) retry_backoff_ms: i64,

    /// `retry.backoff.max.ms` - Maximum wait time before retrying a failed request.
    /// Default: 1000 ms.
    pub(crate) retry_backoff_max_ms: i64,

    // --- Socket ---
    /// `send.buffer.bytes` - TCP send buffer size. Default: 131072 (128 KiB).
    pub(crate) send_buffer_bytes: i32,

    /// `receive.buffer.bytes` - TCP receive buffer size. Default: 32768 (32 KiB).
    pub(crate) receive_buffer_bytes: i32,

    /// `socket.connection.setup.timeout.ms` - Timeout for socket connection setup.
    /// Default: 10000 ms.
    pub(crate) socket_connection_setup_timeout_ms: i64,

    /// `socket.connection.setup.timeout.max.ms` - Maximum timeout for socket connection
    /// setup. Default: 30000 ms.
    pub(crate) socket_connection_setup_timeout_max_ms: i64,

    // --- Metadata ---
    /// `metadata.max.age.ms` - Period after which metadata is force-refreshed.
    /// Default: 300000 ms (5 minutes).
    pub(crate) metadata_max_age_ms: i64,

    /// `metadata.max.idle.ms` - Controls how long the producer will cache metadata for
    /// an idle topic. Default: 300000 ms (5 minutes).
    pub(crate) metadata_max_idle_ms: i64,

    // --- Partitioning ---
    /// `partitioner.adaptive.partitioning.enable` - Adapt to broker performance.
    /// Default: true.
    pub(crate) partitioner_adaptive_partitioning_enable: bool,

    /// `partitioner.availability.timeout.ms` - Timeout to mark a partition as
    /// unavailable. Default: 0 (disabled).
    pub(crate) partitioner_availability_timeout_ms: i64,

    /// `partitioner.ignore.keys` - Ignore record keys for partitioning.
    /// Default: false.
    pub(crate) partitioner_ignore_keys: bool,

    // --- Transactions ---
    /// `transactional.id` - TransactionalId for transactional delivery.
    /// Default: `None` (no transactions).
    pub(crate) transactional_id: Option<String>,

    /// `transaction.timeout.ms` - Maximum time a transaction will remain open.
    /// Default: 60000 ms.
    pub(crate) transaction_timeout_ms: i32,

    // --- Metrics ---
    /// `metrics.sample.window.ms` - The window of time a metrics sample is
    /// computed over. Default: 30000 ms.
    pub(crate) metrics_sample_window_ms: i64,

    /// `metrics.num.samples` - The number of samples maintained to compute
    /// metrics. Default: 2.
    pub(crate) metrics_num_samples: i32,

    /// `metrics.recording.level` - The highest recording level for metrics.
    /// One of `INFO`, `DEBUG`, `TRACE`. Default: `INFO`.
    pub(crate) metrics_recording_level: String,
}

impl Default for ProducerConfig {
    fn default() -> Self {
        Self {
            bootstrap_servers: Vec::new(),
            client_id: String::new(),
            security_protocol: SecurityProtocol::Plaintext,
            sasl_config: SaslConfig::default(),
            ssl_config: SslConfig::default(),
            batch_size: 16384,
            linger_ms: 5,
            buffer_memory: 32 * 1024 * 1024,
            max_block_ms: 60 * 1000,
            acks: -1, // "all"
            retries: i32::MAX,
            delivery_timeout_ms: 120 * 1000,
            request_timeout_ms: 30 * 1000,
            enable_idempotence: true,
            max_request_size: 1024 * 1024,
            max_in_flight_requests_per_connection: 5,
            compression_type: CompressionType::None,
            connections_max_idle_ms: 9 * 60 * 1000,
            reconnect_backoff_ms: 50,
            reconnect_backoff_max_ms: 1000,
            retry_backoff_ms: 100,
            retry_backoff_max_ms: 1000,
            send_buffer_bytes: 128 * 1024,
            receive_buffer_bytes: 32 * 1024,
            socket_connection_setup_timeout_ms: 10_000,
            socket_connection_setup_timeout_max_ms: 30_000,
            metadata_max_age_ms: 5 * 60 * 1000,
            metadata_max_idle_ms: 5 * 60 * 1000,
            partitioner_adaptive_partitioning_enable: true,
            partitioner_availability_timeout_ms: 0,
            partitioner_ignore_keys: false,
            transactional_id: None,
            transaction_timeout_ms: 60_000,
            metrics_sample_window_ms: 30_000,
            metrics_num_samples: 2,
            metrics_recording_level: "INFO".to_string(),
        }
    }
}

impl ProducerConfig {
    /// Creates a new `ProducerConfig` with default values.
    pub fn new() -> Self {
        Self::default()
    }

    /// Maximum number of in-flight requests per connection when idempotence is enabled.
    pub const MAX_IN_FLIGHT_REQUESTS_FOR_IDEMPOTENCE: i32 = MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION_FOR_IDEMPOTENCE;

    // --- Config key constants (matching Java string keys) ---

    /// Config key: `bootstrap.servers`
    pub const BOOTSTRAP_SERVERS_CONFIG: &'static str = "bootstrap.servers";
    /// Config key: `client.id`
    pub const CLIENT_ID_CONFIG: &'static str = "client.id";
    /// Config key: `batch.size`
    pub const BATCH_SIZE_CONFIG: &'static str = "batch.size";
    /// Config key: `linger.ms`
    pub const LINGER_MS_CONFIG: &'static str = "linger.ms";
    /// Config key: `buffer.memory`
    pub const BUFFER_MEMORY_CONFIG: &'static str = "buffer.memory";
    /// Config key: `max.block.ms`
    pub const MAX_BLOCK_MS_CONFIG: &'static str = "max.block.ms";
    /// Config key: `acks`
    pub const ACKS_CONFIG: &'static str = "acks";
    /// Config key: `retries`
    pub const RETRIES_CONFIG: &'static str = "retries";
    /// Config key: `delivery.timeout.ms`
    pub const DELIVERY_TIMEOUT_MS_CONFIG: &'static str = "delivery.timeout.ms";
    /// Config key: `request.timeout.ms`
    pub const REQUEST_TIMEOUT_MS_CONFIG: &'static str = "request.timeout.ms";
    /// Config key: `enable.idempotence`
    pub const ENABLE_IDEMPOTENCE_CONFIG: &'static str = "enable.idempotence";
    /// Config key: `max.request.size`
    pub const MAX_REQUEST_SIZE_CONFIG: &'static str = "max.request.size";
    /// Config key: `max.in.flight.requests.per.connection`
    pub const MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION: &'static str = "max.in.flight.requests.per.connection";
    /// Config key: `compression.type`
    pub const COMPRESSION_TYPE_CONFIG: &'static str = "compression.type";
    /// Config key: `connections.max.idle.ms`
    pub const CONNECTIONS_MAX_IDLE_MS_CONFIG: &'static str = "connections.max.idle.ms";
    /// Config key: `reconnect.backoff.ms`
    pub const RECONNECT_BACKOFF_MS_CONFIG: &'static str = "reconnect.backoff.ms";
    /// Config key: `reconnect.backoff.max.ms`
    pub const RECONNECT_BACKOFF_MAX_MS_CONFIG: &'static str = "reconnect.backoff.max.ms";
    /// Config key: `retry.backoff.ms`
    pub const RETRY_BACKOFF_MS_CONFIG: &'static str = "retry.backoff.ms";
    /// Config key: `retry.backoff.max.ms`
    pub const RETRY_BACKOFF_MAX_MS_CONFIG: &'static str = "retry.backoff.max.ms";
    /// Config key: `send.buffer.bytes`
    pub const SEND_BUFFER_CONFIG: &'static str = "send.buffer.bytes";
    /// Config key: `receive.buffer.bytes`
    pub const RECEIVE_BUFFER_CONFIG: &'static str = "receive.buffer.bytes";
    /// Config key: `metadata.max.age.ms`
    pub const METADATA_MAX_AGE_CONFIG: &'static str = "metadata.max.age.ms";
    /// Config key: `metadata.max.idle.ms`
    pub const METADATA_MAX_IDLE_CONFIG: &'static str = "metadata.max.idle.ms";
    /// Config key: `partitioner.adaptive.partitioning.enable`
    pub const PARTITIONER_ADAPTIVE_PARTITIONING_ENABLE_CONFIG: &'static str =
        "partitioner.adaptive.partitioning.enable";
    /// Config key: `partitioner.availability.timeout.ms`
    pub const PARTITIONER_AVAILABILITY_TIMEOUT_MS_CONFIG: &'static str = "partitioner.availability.timeout.ms";
    /// Config key: `partitioner.ignore.keys`
    pub const PARTITIONER_IGNORE_KEYS_CONFIG: &'static str = "partitioner.ignore.keys";
    /// Config key: `transactional.id`
    pub const TRANSACTIONAL_ID_CONFIG: &'static str = "transactional.id";
    /// Config key: `transaction.timeout.ms`
    pub const TRANSACTION_TIMEOUT_CONFIG: &'static str = "transaction.timeout.ms";
    /// Config key: `metrics.sample.window.ms`
    pub const METRICS_SAMPLE_WINDOW_MS_CONFIG: &'static str = "metrics.sample.window.ms";
    /// Config key: `metrics.num.samples`
    pub const METRICS_NUM_SAMPLES_CONFIG: &'static str = "metrics.num.samples";
    /// Config key: `metrics.recording.level`
    pub const METRICS_RECORDING_LEVEL_CONFIG: &'static str = "metrics.recording.level";
    /// Config key: `security.protocol`
    pub const SECURITY_PROTOCOL_CONFIG: &'static str = common_client_configs::SECURITY_PROTOCOL_CONFIG;
    /// Config key: `sasl.mechanism`
    pub const SASL_MECHANISM_CONFIG: &'static str = sasl_configs::SASL_MECHANISM;
    /// Config key: `sasl.jaas.config`
    pub const SASL_JAAS_CONFIG: &'static str = sasl_configs::SASL_JAAS_CONFIG;

    /// Creates a `ProducerConfig` from a map of string key-value pairs.
    ///
    /// This is the Rust equivalent of Java's `new ProducerConfig(Map<String, Object>)`
    /// or `new ProducerConfig(Properties)`. Starts with default values and overrides
    /// each field that has a matching entry in the map.
    ///
    /// Unknown keys are logged as warnings and ignored, matching Java's behavior.
    ///
    /// # Errors
    ///
    /// Returns [`KafkaError::IllegalArgument`] if a value cannot be parsed for its
    /// expected type (e.g., `"abc"` for an integer field).
    pub fn from_properties(props: &HashMap<String, String>) -> Result<Self, KafkaError> {
        let mut config = Self::default();

        for (key, value) in props {
            match key.as_str() {
                Self::BOOTSTRAP_SERVERS_CONFIG => {
                    config.bootstrap_servers = value.split(',').map(|s| s.trim().to_string()).collect();
                },
                Self::CLIENT_ID_CONFIG => {
                    config.client_id = value.to_string();
                },
                Self::BATCH_SIZE_CONFIG => {
                    config.batch_size = Self::parse_i32(key, value)?;
                },
                Self::LINGER_MS_CONFIG => {
                    config.linger_ms = Self::parse_i64(key, value)?;
                },
                Self::BUFFER_MEMORY_CONFIG => {
                    config.buffer_memory = Self::parse_i64(key, value)?;
                },
                Self::MAX_BLOCK_MS_CONFIG => {
                    config.max_block_ms = Self::parse_i64(key, value)?;
                },
                Self::ACKS_CONFIG => {
                    config.acks = Self::parse_acks(value).map_err(KafkaError::illegal_argument)?;
                },
                Self::RETRIES_CONFIG => {
                    config.retries = Self::parse_i32(key, value)?;
                },
                Self::DELIVERY_TIMEOUT_MS_CONFIG => {
                    config.delivery_timeout_ms = Self::parse_i32(key, value)?;
                },
                Self::REQUEST_TIMEOUT_MS_CONFIG => {
                    config.request_timeout_ms = Self::parse_i32(key, value)?;
                },
                Self::ENABLE_IDEMPOTENCE_CONFIG => {
                    config.enable_idempotence = Self::parse_bool(key, value)?;
                },
                Self::MAX_REQUEST_SIZE_CONFIG => {
                    config.max_request_size = Self::parse_i32(key, value)?;
                },
                Self::MAX_IN_FLIGHT_REQUESTS_PER_CONNECTION => {
                    config.max_in_flight_requests_per_connection = Self::parse_i32(key, value)?;
                },
                Self::COMPRESSION_TYPE_CONFIG => {
                    config.compression_type = CompressionType::for_name(value)?;
                },
                Self::CONNECTIONS_MAX_IDLE_MS_CONFIG => {
                    config.connections_max_idle_ms = Self::parse_i64(key, value)?;
                },
                Self::RECONNECT_BACKOFF_MS_CONFIG => {
                    config.reconnect_backoff_ms = Self::parse_i64(key, value)?;
                },
                Self::RECONNECT_BACKOFF_MAX_MS_CONFIG => {
                    config.reconnect_backoff_max_ms = Self::parse_i64(key, value)?;
                },
                Self::RETRY_BACKOFF_MS_CONFIG => {
                    config.retry_backoff_ms = Self::parse_i64(key, value)?;
                },
                Self::RETRY_BACKOFF_MAX_MS_CONFIG => {
                    config.retry_backoff_max_ms = Self::parse_i64(key, value)?;
                },
                Self::SEND_BUFFER_CONFIG => {
                    config.send_buffer_bytes = Self::parse_i32(key, value)?;
                },
                Self::RECEIVE_BUFFER_CONFIG => {
                    config.receive_buffer_bytes = Self::parse_i32(key, value)?;
                },
                Self::METADATA_MAX_AGE_CONFIG => {
                    config.metadata_max_age_ms = Self::parse_i64(key, value)?;
                },
                Self::METADATA_MAX_IDLE_CONFIG => {
                    config.metadata_max_idle_ms = Self::parse_i64(key, value)?;
                },
                Self::PARTITIONER_ADAPTIVE_PARTITIONING_ENABLE_CONFIG => {
                    config.partitioner_adaptive_partitioning_enable = Self::parse_bool(key, value)?;
                },
                Self::PARTITIONER_AVAILABILITY_TIMEOUT_MS_CONFIG => {
                    config.partitioner_availability_timeout_ms = Self::parse_i64(key, value)?;
                },
                Self::PARTITIONER_IGNORE_KEYS_CONFIG => {
                    config.partitioner_ignore_keys = Self::parse_bool(key, value)?;
                },
                Self::TRANSACTIONAL_ID_CONFIG => {
                    config.transactional_id = if value.is_empty() {
                        None
                    } else {
                        Some(value.to_string())
                    };
                },
                Self::TRANSACTION_TIMEOUT_CONFIG => {
                    config.transaction_timeout_ms = Self::parse_i32(key, value)?;
                },
                Self::METRICS_SAMPLE_WINDOW_MS_CONFIG => {
                    // Java `ProducerConfig` / `CommonClientConfigs`:
                    // `metrics.sample.window.ms` is `atLeast(0)`.
                    let v = Self::parse_i64(key, value)?;
                    if v < 0 {
                        return Err(KafkaError::illegal_argument(format!(
                            "Invalid value {v} for configuration {key}: Value must be at least 0"
                        )));
                    }
                    config.metrics_sample_window_ms = v;
                },
                Self::METRICS_NUM_SAMPLES_CONFIG => {
                    // Java `ProducerConfig` / `CommonClientConfigs`:
                    // `metrics.num.samples` is `atLeast(1)`.
                    let v = Self::parse_i32(key, value)?;
                    if v < 1 {
                        return Err(KafkaError::illegal_argument(format!(
                            "Invalid value {v} for configuration {key}: Value must be at least 1"
                        )));
                    }
                    config.metrics_num_samples = v;
                },
                Self::METRICS_RECORDING_LEVEL_CONFIG => {
                    let uc = value.to_ascii_uppercase();
                    if uc != "INFO" && uc != "DEBUG" && uc != "TRACE" {
                        return Err(KafkaError::illegal_argument(format!(
                            "Invalid value for '{}': {}",
                            Self::METRICS_RECORDING_LEVEL_CONFIG,
                            value
                        )));
                    }
                    config.metrics_recording_level = value.to_string();
                },
                Self::SECURITY_PROTOCOL_CONFIG => {
                    config.security_protocol = SecurityProtocol::for_name(value).ok_or_else(|| {
                        KafkaError::illegal_argument(format!(
                            "Invalid value for '{}': {}. Valid values are: {:?}",
                            key,
                            value,
                            SecurityProtocol::names()
                        ))
                    })?;
                },
                Self::SASL_MECHANISM_CONFIG => {
                    config.sasl_config.mechanism = value.to_string();
                },
                Self::SASL_JAAS_CONFIG => {
                    config.sasl_config.jaas_config = if value.is_empty() {
                        None
                    } else {
                        Some(value.to_string())
                    };
                },
                key if key.starts_with("ssl.") => {
                    ssl_configs::apply_ssl_config_key(&mut config.ssl_config, key, value);
                },
                _ => {
                    warn!("Unknown producer configuration key: {}", key);
                },
            }
        }

        Ok(config)
    }

    /// Parses a string value as `i32`.
    fn parse_i32(key: &str, value: &str) -> Result<i32, KafkaError> {
        value
            .trim()
            .parse::<i32>()
            .map_err(|_| KafkaError::illegal_argument(format!("Invalid value for '{}': {}", key, value)))
    }

    /// Parses a string value as `i64`.
    fn parse_i64(key: &str, value: &str) -> Result<i64, KafkaError> {
        value
            .trim()
            .parse::<i64>()
            .map_err(|_| KafkaError::illegal_argument(format!("Invalid value for '{}': {}", key, value)))
    }

    /// Parses a string value as `bool`.
    fn parse_bool(key: &str, value: &str) -> Result<bool, KafkaError> {
        match value.trim() {
            "true" => Ok(true),
            "false" => Ok(false),
            _ => Err(KafkaError::illegal_argument(format!("Invalid value for '{}': {}", key, value))),
        }
    }

    /// Parses the acks string, converting "all" to -1.
    pub fn parse_acks(acks_string: &str) -> Result<i16, String> {
        let trimmed = acks_string.trim();
        if trimmed.eq_ignore_ascii_case("all") {
            Ok(-1)
        } else {
            trimmed
                .parse::<i16>()
                .map_err(|_| format!("Invalid configuration value for 'acks': {acks_string}"))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_values() {
        let config = ProducerConfig::default();
        assert_eq!(config.batch_size, 16384);
        assert_eq!(config.linger_ms, 5);
        assert_eq!(config.buffer_memory, 32 * 1024 * 1024);
        assert_eq!(config.max_block_ms, 60_000);
        assert_eq!(config.acks, -1);
        assert_eq!(config.retries, i32::MAX);
        assert_eq!(config.delivery_timeout_ms, 120_000);
        assert_eq!(config.request_timeout_ms, 30_000);
        assert!(config.enable_idempotence);
        assert_eq!(config.max_request_size, 1_048_576);
        assert_eq!(config.max_in_flight_requests_per_connection, 5);
        assert_eq!(config.compression_type, CompressionType::None);
        assert_eq!(config.connections_max_idle_ms, 540_000);
        assert_eq!(config.reconnect_backoff_ms, 50);
        assert_eq!(config.reconnect_backoff_max_ms, 1000);
        assert_eq!(config.retry_backoff_ms, 100);
        assert_eq!(config.retry_backoff_max_ms, 1000);
        assert_eq!(config.send_buffer_bytes, 131_072);
        assert_eq!(config.receive_buffer_bytes, 32_768);
        assert_eq!(config.metadata_max_age_ms, 300_000);
        assert_eq!(config.metadata_max_idle_ms, 300_000);
        assert!(config.partitioner_adaptive_partitioning_enable);
        assert_eq!(config.partitioner_availability_timeout_ms, 0);
        assert!(!config.partitioner_ignore_keys);
        assert!(config.transactional_id.is_none());
        assert_eq!(config.transaction_timeout_ms, 60_000);
        assert_eq!(config.metrics_sample_window_ms, 30_000);
        assert_eq!(config.metrics_num_samples, 2);
        assert_eq!(config.metrics_recording_level, "INFO");
    }

    /// `metrics.num.samples` is `atLeast(1)` (Java ProducerConfig /
    /// CommonClientConfigs). A value below 1 is rejected asserting the bound.
    #[test]
    fn test_metrics_num_samples_validator() {
        let mut props = HashMap::new();
        props.insert("metrics.num.samples".to_string(), "3".to_string());
        let c = ProducerConfig::from_properties(&props).unwrap();
        assert_eq!(c.metrics_num_samples, 3);

        let mut props = HashMap::new();
        props.insert("metrics.num.samples".to_string(), "0".to_string());
        let err = ProducerConfig::from_properties(&props).unwrap_err();
        let msg = err.to_string();
        assert!(
            msg.contains("metrics.num.samples") && msg.contains("at least 1"),
            "unexpected message: {msg}"
        );

        let mut props = HashMap::new();
        props.insert("metrics.num.samples".to_string(), "-1".to_string());
        assert!(ProducerConfig::from_properties(&props).is_err());
    }

    /// `metrics.sample.window.ms` is `atLeast(0)` (Java ProducerConfig /
    /// CommonClientConfigs). A negative value is rejected asserting the bound.
    #[test]
    fn test_metrics_sample_window_ms_validator() {
        let mut props = HashMap::new();
        props.insert("metrics.sample.window.ms".to_string(), "0".to_string());
        let c = ProducerConfig::from_properties(&props).unwrap();
        assert_eq!(c.metrics_sample_window_ms, 0);

        let mut props = HashMap::new();
        props.insert("metrics.sample.window.ms".to_string(), "60000".to_string());
        let c = ProducerConfig::from_properties(&props).unwrap();
        assert_eq!(c.metrics_sample_window_ms, 60_000);

        let mut props = HashMap::new();
        props.insert("metrics.sample.window.ms".to_string(), "-1".to_string());
        let err = ProducerConfig::from_properties(&props).unwrap_err();
        let msg = err.to_string();
        assert!(
            msg.contains("metrics.sample.window.ms") && msg.contains("at least 0"),
            "unexpected message: {msg}"
        );
    }

    /// `metrics.recording.level` accepts INFO/DEBUG/TRACE (case-insensitive)
    /// and rejects anything else.
    #[test]
    fn test_metrics_recording_level_validator() {
        let mut props = HashMap::new();
        props.insert("metrics.recording.level".to_string(), "DEBUG".to_string());
        let c = ProducerConfig::from_properties(&props).unwrap();
        assert_eq!(c.metrics_recording_level, "DEBUG");

        let mut props = HashMap::new();
        props.insert("metrics.recording.level".to_string(), "bogus".to_string());
        assert!(ProducerConfig::from_properties(&props).is_err());
    }

    #[test]
    fn test_from_properties_basic() {
        let mut props = HashMap::new();
        props.insert("bootstrap.servers".to_string(), "host1:9092,host2:9093".to_string());
        props.insert("client.id".to_string(), "my-producer".to_string());
        props.insert("batch.size".to_string(), "32768".to_string());
        props.insert("linger.ms".to_string(), "10".to_string());
        props.insert("acks".to_string(), "all".to_string());
        props.insert("compression.type".to_string(), "gzip".to_string());
        props.insert("enable.idempotence".to_string(), "false".to_string());

        let config = ProducerConfig::from_properties(&props).unwrap();
        assert_eq!(config.bootstrap_servers, vec!["host1:9092", "host2:9093"]);
        assert_eq!(config.client_id, "my-producer");
        assert_eq!(config.batch_size, 32768);
        assert_eq!(config.linger_ms, 10);
        assert_eq!(config.acks, -1);
        assert_eq!(config.compression_type, CompressionType::Gzip);
        assert!(!config.enable_idempotence);
    }

    #[test]
    fn test_from_properties_defaults_for_missing() {
        let props = HashMap::new();
        let config = ProducerConfig::from_properties(&props).unwrap();
        // All fields should have default values
        assert_eq!(config.batch_size, 16384);
        assert_eq!(config.linger_ms, 5);
        assert_eq!(config.acks, -1);
    }

    #[test]
    fn test_from_properties_invalid_value() {
        let mut props = HashMap::new();
        props.insert("batch.size".to_string(), "not-a-number".to_string());
        let result = ProducerConfig::from_properties(&props);
        assert!(result.is_err());
    }

    #[test]
    fn test_from_properties_unknown_key_ignored() {
        let mut props = HashMap::new();
        props.insert("unknown.key".to_string(), "value".to_string());
        props.insert("bootstrap.servers".to_string(), "localhost:9092".to_string());
        let config = ProducerConfig::from_properties(&props).unwrap();
        assert_eq!(config.bootstrap_servers, vec!["localhost:9092"]);
    }

    #[test]
    fn test_from_properties_transactional_id() {
        let mut props = HashMap::new();
        props.insert("transactional.id".to_string(), "my-txn".to_string());
        let config = ProducerConfig::from_properties(&props).unwrap();
        assert_eq!(config.transactional_id, Some("my-txn".to_string()));

        // Empty string -> None
        let mut props = HashMap::new();
        props.insert("transactional.id".to_string(), String::new());
        let config = ProducerConfig::from_properties(&props).unwrap();
        assert_eq!(config.transactional_id, None);
    }

    #[test]
    fn test_parse_acks() {
        assert_eq!(ProducerConfig::parse_acks("all"), Ok(-1));
        assert_eq!(ProducerConfig::parse_acks("ALL"), Ok(-1));
        assert_eq!(ProducerConfig::parse_acks("-1"), Ok(-1));
        assert_eq!(ProducerConfig::parse_acks("0"), Ok(0));
        assert_eq!(ProducerConfig::parse_acks("1"), Ok(1));
        assert!(ProducerConfig::parse_acks("invalid").is_err());
    }

    /// Translated from `ProducerConfigTest.testInvalidSecurityProtocol`.
    #[test]
    fn test_invalid_security_protocol() {
        let mut props = HashMap::new();
        props.insert("security.protocol".to_string(), "abc".to_string());
        props.insert("bootstrap.servers".to_string(), "localhost:9092".to_string());
        let err = ProducerConfig::from_properties(&props).unwrap_err();
        let msg = format!("{}", err);
        assert!(
            msg.contains("security.protocol"),
            "Error message should contain config key, got: {}",
            msg
        );
    }

    /// Translated from `ProducerConfigTest.testCaseInsensitiveSecurityProtocol`.
    #[test]
    fn test_case_insensitive_security_protocol() {
        let mut props = HashMap::new();
        props.insert("security.protocol".to_string(), "sasl_ssl".to_string());
        props.insert("bootstrap.servers".to_string(), "localhost:9092".to_string());
        let config = ProducerConfig::from_properties(&props).unwrap();
        assert_eq!(config.security_protocol, SecurityProtocol::SaslSsl);
    }

    #[test]
    fn test_sasl_config_from_properties() {
        let mut props = HashMap::new();
        props.insert("sasl.mechanism".to_string(), "PLAIN".to_string());
        props.insert(
            "sasl.jaas.config".to_string(),
            "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"alice\" password=\"secret\";"
                .to_string(),
        );
        props.insert("bootstrap.servers".to_string(), "localhost:9092".to_string());
        let config = ProducerConfig::from_properties(&props).unwrap();
        assert_eq!(config.sasl_config.mechanism, "PLAIN");
        assert_eq!(config.sasl_config.resolve_username(), Some("alice"));
        assert_eq!(config.sasl_config.resolve_password(), Some("secret"));
    }

    #[test]
    fn test_ssl_config_from_properties() {
        let mut props = HashMap::new();
        props.insert("ssl.truststore.location".to_string(), "/path/to/truststore.pem".to_string());
        props.insert("ssl.keystore.location".to_string(), "/path/to/keystore.pem".to_string());
        props.insert("ssl.endpoint.identification.algorithm".to_string(), String::new());
        props.insert("bootstrap.servers".to_string(), "localhost:9092".to_string());
        let config = ProducerConfig::from_properties(&props).unwrap();
        assert_eq!(
            config.ssl_config.truststore_location.as_deref(),
            Some("/path/to/truststore.pem")
        );
        assert_eq!(config.ssl_config.keystore_location.as_deref(), Some("/path/to/keystore.pem"));
        assert_eq!(config.ssl_config.endpoint_identification_algorithm, "");
    }
}
