/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=message-specs/");
    println!("cargo:rerun-if-changed=src/message/");
    
    let out_dir = env::var("OUT_DIR").unwrap();
    let generated_dir = Path::new(&out_dir).join("generated");
    fs::create_dir_all(&generated_dir).unwrap();
    
    // Get all JSON spec files
    let specs_dir = PathBuf::from("message-specs");
    let spec_files = collect_spec_files(&specs_dir);
    
    eprintln!("Generating code for {} message specifications", spec_files.len());
    
    // Generate module file that includes all generated messages
    let mut mod_content = String::from(r#"// Generated message definitions
// This file is automatically generated during build from JSON specifications

"#);
    
    let mut generated_count = 0;
    let mut parse_success_count = 0;
    
    for spec_file in &spec_files {
        if let Some(name) = spec_file.file_stem().and_then(|s| s.to_str()) {
            let module_name = to_snake_case(name);
            
            // Try to parse and generate the message
            match generate_message_from_spec(&spec_file, name) {
                Ok((message_content, parsed)) => {
                    let message_path = generated_dir.join(format!("{}.rs", module_name));
                    fs::write(&message_path, message_content).unwrap();
                    mod_content.push_str(&format!("pub mod {};\n", module_name));
                    generated_count += 1;
                    if parsed {
                        parse_success_count += 1;
                    }
                }
                Err(e) => {
                    // For specs that fail to parse, generate a stub
                    eprintln!("Warning: Failed to generate {}: {}", name, e);
                    let message_content = generate_message_stub(name);
                    let message_path = generated_dir.join(format!("{}.rs", module_name));
                    fs::write(&message_path, message_content).unwrap();
                    mod_content.push_str(&format!("pub mod {};\n", module_name));
                    generated_count += 1;
                }
            }
        }
    }
    
    // Write the main module file
    let mod_path = generated_dir.join("mod.rs");
    fs::write(&mod_path, mod_content).unwrap();
    
    eprintln!("Successfully generated {} message modules ({} fully parsed)", 
             generated_count, parse_success_count);
    eprintln!("Generated code at: {:?}", generated_dir);
}

fn collect_spec_files(dir: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.filter_map(Result::ok) {
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) == Some("json") {
                files.push(path);
            }
        }
    }
    
    files.sort();
    files
}

fn generate_message_from_spec(path: &Path, name: &str) -> Result<(String, bool), String> {
    // Read and parse the JSON file
    let content = fs::read_to_string(path)
        .map_err(|e| format!("Failed to read file: {}", e))?;
    
    // Strip JSON comments (lines starting with //)
    let cleaned_content: String = content
        .lines()
        .filter(|line| !line.trim().starts_with("//"))
        .collect::<Vec<_>>()
        .join("\n");
    
    // Try to parse the JSON into a simple structure to extract basic info
    let json_value: serde_json::Value = serde_json::from_str(&cleaned_content)
        .map_err(|e| format!("Failed to parse JSON: {}", e))?;
    
    let api_key = json_value.get("apiKey").and_then(|v| v.as_i64());
    let msg_type = json_value.get("type").and_then(|v| v.as_str()).unwrap_or("unknown");
    let valid_versions = json_value.get("validVersions").and_then(|v| v.as_str()).unwrap_or("0+");
    let flexible_versions = json_value.get("flexibleVersions").and_then(|v| v.as_str()).unwrap_or("none");
    let fields = json_value.get("fields").and_then(|v| v.as_array());
    let common_structs = json_value.get("commonStructs").and_then(|v| v.as_array());
    
    // Collect all nested struct definitions from fields
    let mut nested_structs = Vec::new();
    if let Some(field_array) = fields {
        collect_nested_structs(field_array, &mut nested_structs);
    }
    
    // Add common structs (defined at top level)
    if let Some(common_array) = common_structs {
        for common_struct in common_array {
            if let Some(struct_name) = common_struct.get("name").and_then(|v| v.as_str()) {
                if let Some(struct_fields) = common_struct.get("fields").and_then(|v| v.as_array()) {
                    nested_structs.push((struct_name.to_string(), struct_fields.clone()));
                }
            }
        }
    }
    
    // Generate the struct with extracted information
    let mut output = String::new();
    
    output.push_str(&format!("// Generated from {}.json\n", name));
    output.push_str("//\n");
    if let Some(key) = api_key {
        output.push_str(&format!("// API Key: {}\n", key));
    }
    output.push_str(&format!("// Type: {}\n", msg_type));
    output.push_str(&format!("// Valid Versions: {}\n", valid_versions));
    output.push_str(&format!("// Flexible Versions: {}\n", flexible_versions));
    output.push_str("\n");
    
    // Always add protocol imports for read/write methods
    // Use super::super to go from generated::<module> to crate root
    // Allow unused imports for messages that don't have serialization methods
    output.push_str("#[allow(unused_imports)]\n");
    output.push_str("use super::super::common::protocol::{Readable, Writable};\n");
    
    // Check if we need to import Uuid
    let needs_uuid = check_fields_need_uuid(fields) || 
                     check_common_structs_need_uuid(common_structs);
    
    if needs_uuid {
        output.push_str("use super::super::common::Uuid;\n");
    }
    output.push_str("\n");
    
    // Generate nested struct definitions first
    for (struct_name, struct_fields) in &nested_structs {
        output.push_str(&generate_struct_def(struct_name, struct_fields));
    }
    
    // Generate the main struct
    output.push_str("#[derive(Debug, Clone)]\n");
    output.push_str("#[allow(dead_code)]\n");
    output.push_str(&format!("pub struct {} {{\n", data_class_name(name, msg_type)));
    
    // Generate fields if available
    if let Some(field_array) = fields {
        for field in field_array {
            if let Some(field_name) = field.get("name").and_then(|v| v.as_str()) {
                let field_type = field.get("type").and_then(|v| v.as_str()).unwrap_or("string");
                let about = field.get("about").and_then(|v| v.as_str()).unwrap_or("");
                
                let rust_type = resolve_field_type(field_type);
                let snake_name = to_snake_case(field_name);
                let escaped_name = escape_rust_keyword(&snake_name);
                
                output.push_str(&format!("    /// {}\n", about));
                output.push_str(&format!("    pub {}: {},\n", escaped_name, rust_type));
            }
        }
    } else {
        output.push_str("    // Fields will be generated from JSON specification\n");
    }
    
    output.push_str("}\n\n");
    
    // Generate impl block
    output.push_str(&format!("impl {} {{\n", data_class_name(name, msg_type)));
    output.push_str("    #[allow(dead_code)]\n");
    output.push_str("    pub fn new() -> Self {\n");
    output.push_str(&format!("        {} {{\n", data_class_name(name, msg_type)));
    
    if let Some(field_array) = fields {
        for field in field_array {
            if let Some(field_name) = field.get("name").and_then(|v| v.as_str()) {
                let field_type = field.get("type").and_then(|v| v.as_str()).unwrap_or("string");
                let snake_name = to_snake_case(field_name);
                let escaped_name = escape_rust_keyword(&snake_name);
                let default_val = default_value_for_type(field_type);
                output.push_str(&format!("            {}: {},\n", escaped_name, default_val));
            }
        }
    }
    
    output.push_str("        }\n");
    output.push_str("    }\n");
    
    // Add version constants
    let (lowest, highest) = parse_version_range(valid_versions);
    output.push_str("\n");
    output.push_str(&format!("    pub const LOWEST_SUPPORTED_VERSION: i16 = {};\n", lowest));
    output.push_str(&format!("    pub const HIGHEST_SUPPORTED_VERSION: i16 = {};\n", highest));
    
    if let Some(key) = api_key {
        output.push_str(&format!("    pub const API_KEY: i16 = {};\n", key));
    }
    
    // Generate read() method
    if let Some(field_array) = fields {
        output.push_str("\n");
        output.push_str("    /// Deserialize this message from the Kafka wire protocol\n");
        output.push_str("    #[allow(unused_variables)]\n");
        output.push_str("    pub fn read(readable: &mut dyn Readable, version: i16) -> std::io::Result<Self> {\n");
        output.push_str(&format!("        if version < {} || version > {} {{\n", lowest, highest));
        output.push_str("            return Err(std::io::Error::new(\n");
        output.push_str("                std::io::ErrorKind::InvalidData,\n");
        output.push_str(&format!("                format!(\"Unsupported version: {{}}\", version),\n"));
        output.push_str("            ));\n");
        output.push_str("        }\n\n");
        output.push_str("        let mut result = Self::new();\n");
        
        for field in field_array {
            if let Some(field_name) = field.get("name").and_then(|v| v.as_str()) {
                let field_type = field.get("type").and_then(|v| v.as_str()).unwrap_or("string");
                let snake_name = to_snake_case(field_name);
                let escaped_name = escape_rust_keyword(&snake_name);
                
                output.push_str(&generate_field_read(&escaped_name, field_type));
            }
        }
        
        output.push_str("        Ok(result)\n");
        output.push_str("    }\n");
        
        // Generate write() method
        output.push_str("\n");
        output.push_str("    /// Serialize this message to the Kafka wire protocol\n");
        output.push_str("    #[allow(unused_variables)]\n");
        output.push_str("    pub fn write(&self, writable: &mut dyn Writable, version: i16) -> std::io::Result<()> {\n");
        output.push_str(&format!("        if version < {} || version > {} {{\n", lowest, highest));
        output.push_str("            return Err(std::io::Error::new(\n");
        output.push_str("                std::io::ErrorKind::InvalidData,\n");
        output.push_str(&format!("                format!(\"Unsupported version: {{}}\", version),\n"));
        output.push_str("            ));\n");
        output.push_str("        }\n\n");
        
        for field in field_array {
            if let Some(field_name) = field.get("name").and_then(|v| v.as_str()) {
                let field_type = field.get("type").and_then(|v| v.as_str()).unwrap_or("string");
                let snake_name = to_snake_case(field_name);
                let escaped_name = escape_rust_keyword(&snake_name);
                
                output.push_str(&generate_field_write(&escaped_name, field_type));
            }
        }
        
        output.push_str("        Ok(())\n");
        output.push_str("    }\n");
    }
    
    output.push_str("}\n");
    
    let fully_parsed = fields.is_some();
    Ok((output, fully_parsed))
}

/// Check if any field in the array uses uuid type
fn check_fields_need_uuid(fields: Option<&Vec<serde_json::Value>>) -> bool {
    if let Some(field_array) = fields {
        for field in field_array {
            if let Some(field_type) = field.get("type").and_then(|v| v.as_str()) {
                if field_type == "uuid" || field_type.contains("[]uuid") {
                    return true;
                }
                // Check nested fields recursively
                if let Some(nested_fields) = field.get("fields").and_then(|v| v.as_array()) {
                    if check_fields_need_uuid(Some(nested_fields)) {
                        return true;
                    }
                }
            }
        }
    }
    false
}

/// Check if any commonStruct uses uuid type
fn check_common_structs_need_uuid(common_structs: Option<&Vec<serde_json::Value>>) -> bool {
    if let Some(common_array) = common_structs {
        for common_struct in common_array {
            if let Some(struct_fields) = common_struct.get("fields").and_then(|v| v.as_array()) {
                if check_fields_need_uuid(Some(struct_fields)) {
                    return true;
                }
            }
        }
    }
    false
}

/// Recursively collect all nested struct definitions from fields
fn collect_nested_structs(fields: &[serde_json::Value], structs: &mut Vec<(String, Vec<serde_json::Value>)>) {
    for field in fields {
        if let Some(field_type) = field.get("type").and_then(|v| v.as_str()) {
            // Check if this is an array of structs (e.g., []OffsetForLeaderTopic)
            let base_type = if field_type.starts_with("[]") {
                &field_type[2..]
            } else {
                field_type
            };
            
            // If the field has nested fields, it's a struct type
            if let Some(nested_fields) = field.get("fields").and_then(|v| v.as_array()) {
                // Recursively collect nested structs from these fields
                collect_nested_structs(nested_fields, structs);
                
                // Add this struct definition
                structs.push((base_type.to_string(), nested_fields.clone()));
            }
        }
    }
}

/// Generate a struct definition from a name and fields
fn generate_struct_def(struct_name: &str, fields: &[serde_json::Value]) -> String {
    let mut output = String::new();
    
    output.push_str(&format!("/// Nested struct for {}\n", struct_name));
    output.push_str("#[derive(Debug, Clone)]\n");
    output.push_str("#[allow(dead_code)]\n");
    output.push_str(&format!("pub struct {} {{\n", struct_name));
    
    for field in fields {
        if let Some(field_name) = field.get("name").and_then(|v| v.as_str()) {
            let field_type = field.get("type").and_then(|v| v.as_str()).unwrap_or("string");
            let about = field.get("about").and_then(|v| v.as_str()).unwrap_or("");
            
            let rust_type = resolve_field_type(field_type);
            let snake_name = to_snake_case(field_name);
            let escaped_name = escape_rust_keyword(&snake_name);
            
            output.push_str(&format!("    /// {}\n", about));
            output.push_str(&format!("    pub {}: {},\n", escaped_name, rust_type));
        }
    }
    
    output.push_str("}\n\n");
    
    // Generate impl block with constructor
    output.push_str(&format!("impl {} {{\n", struct_name));
    output.push_str("    #[allow(dead_code)]\n");
    output.push_str("    pub fn new() -> Self {\n");
    output.push_str(&format!("        {} {{\n", struct_name));
    
    for field in fields {
        if let Some(field_name) = field.get("name").and_then(|v| v.as_str()) {
            let field_type = field.get("type").and_then(|v| v.as_str()).unwrap_or("string");
            let snake_name = to_snake_case(field_name);
            let escaped_name = escape_rust_keyword(&snake_name);
            let default_val = default_value_for_type(field_type);
            output.push_str(&format!("            {}: {},\n", escaped_name, default_val));
        }
    }
    
    output.push_str("        }\n");
    output.push_str("    }\n");
    
    // Generate read() method for nested structs
    output.push_str("\n");
    output.push_str("    /// Deserialize this nested struct from the Kafka wire protocol\n");
    output.push_str("    #[allow(unused_variables)]\n");
    output.push_str("    pub fn read(readable: &mut dyn Readable, version: i16) -> std::io::Result<Self> {\n");
    output.push_str("        let mut result = Self::new();\n");
    
    for field in fields {
        if let Some(field_name) = field.get("name").and_then(|v| v.as_str()) {
            let field_type = field.get("type").and_then(|v| v.as_str()).unwrap_or("string");
            let snake_name = to_snake_case(field_name);
            let escaped_name = escape_rust_keyword(&snake_name);
            
            output.push_str(&generate_field_read(&escaped_name, field_type));
        }
    }
    
    output.push_str("        Ok(result)\n");
    output.push_str("    }\n");
    
    // Generate write() method for nested structs
    output.push_str("\n");
    output.push_str("    /// Serialize this nested struct to the Kafka wire protocol\n");
    output.push_str("    #[allow(unused_variables)]\n");
    output.push_str("    pub fn write(&self, writable: &mut dyn Writable, version: i16) -> std::io::Result<()> {\n");
    
    for field in fields {
        if let Some(field_name) = field.get("name").and_then(|v| v.as_str()) {
            let field_type = field.get("type").and_then(|v| v.as_str()).unwrap_or("string");
            let snake_name = to_snake_case(field_name);
            let escaped_name = escape_rust_keyword(&snake_name);
            
            output.push_str(&generate_field_write(&escaped_name, field_type));
        }
    }
    
    output.push_str("        Ok(())\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");
    
    output
}

/// Resolve field type, handling both primitive types and struct types
fn resolve_field_type(field_type: &str) -> String {
    if field_type.starts_with("[]") {
        let element_type = &field_type[2..];
        return format!("Vec<{}>", resolve_field_type(element_type));
    }
    
    match field_type {
        "bool" => "bool".to_string(),
        "int8" => "i8".to_string(),
        "int16" => "i16".to_string(),
        "int32" => "i32".to_string(),
        "int64" => "i64".to_string(),
        "uint16" => "u16".to_string(),
        "uint32" => "u32".to_string(),
        "uuid" => "Uuid".to_string(),
        "float64" => "f64".to_string(),
        "string" => "String".to_string(),
        "bytes" => "Vec<u8>".to_string(),
        "records" => "Vec<u8>".to_string(),
        // If it's not a primitive type, it's a struct type - use as-is
        _ => field_type.to_string(),
    }
}

fn data_class_name(name: &str, msg_type: &str) -> String {
    match msg_type {
        "request" | "response" | "header" => format!("{}Data", name),
        _ => name.to_string(),
    }
}

#[allow(dead_code)]
fn simple_type_mapping(field_type: &str) -> String {
    if field_type.starts_with("[]") {
        let element_type = &field_type[2..];
        return format!("Vec<{}>", simple_type_mapping(element_type));
    }
    
    match field_type {
        "bool" => "bool",
        "int8" => "i8",
        "int16" => "i16",
        "int32" => "i32",
        "int64" => "i64",
        "uint16" => "u16",
        "uint32" => "u32",
        "uuid" => "String", // Simplified for now
        "float64" => "f64",
        "string" => "String",
        "bytes" => "Vec<u8>",
        "records" => "Vec<u8>",
        _ => "String", // Default for struct types
    }.to_string()
}

fn default_value_for_type(field_type: &str) -> String {
    if field_type.starts_with("[]") {
        return "Vec::new()".to_string();
    }
    
    match field_type {
        "bool" => "false".to_string(),
        "int8" | "int16" | "int32" | "int64" => "0".to_string(),
        "uint16" | "uint32" => "0".to_string(),
        "float64" => "0.0".to_string(),
        "string" => "String::new()".to_string(),
        "uuid" => "Uuid::zero()".to_string(),
        "bytes" | "records" => "Vec::new()".to_string(),
        // For struct types, use the struct constructor
        _ => format!("{}::new()", field_type),
    }
}

fn parse_version_range(version_str: &str) -> (i16, i16) {
    if version_str == "none" {
        return (0, 0);
    }
    
    if let Some(idx) = version_str.find('+') {
        let lowest = version_str[..idx].parse().unwrap_or(0);
        return (lowest, i16::MAX);
    }
    
    if let Some(idx) = version_str.find('-') {
        let lowest = version_str[..idx].parse().unwrap_or(0);
        let highest = version_str[idx + 1..].parse().unwrap_or(i16::MAX);
        return (lowest, highest);
    }
    
    let version = version_str.parse().unwrap_or(0);
    (version, version)
}

#[allow(dead_code)]
fn is_flexible_version(version: i16, flexible_range: &str) -> bool {
    if flexible_range == "none" {
        return false;
    }
    
    let (flex_lowest, flex_highest) = parse_version_range(flexible_range);
    version >= flex_lowest && version <= flex_highest
}

fn generate_message_stub(name: &str) -> String {
    format!(r#"// Generated from {}.json (stub due to parsing error)

#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct {} {{
    // Fields will be generated from JSON specification
}}

impl {} {{
    #[allow(dead_code)]
    pub fn new() -> Self {{
        {} {{}}
    }}
}}
"#, name, name, name, name)
}

fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    let mut prev_is_lower = false;
    
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 && prev_is_lower {
                result.push('_');
            }
            result.push(ch.to_ascii_lowercase());
            prev_is_lower = false;
        } else {
            result.push(ch);
            prev_is_lower = ch.is_lowercase();
        }
    }
    
    result
}

fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize_next = true;
    
    for ch in s.chars() {
        if ch == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            result.push(ch.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            result.push(ch);
        }
    }
    
    // Ensure first letter is uppercase
    if let Some(first) = result.chars().next() {
        if first.is_lowercase() {
            let mut chars = result.chars();
            chars.next();
            result = format!("{}{}", first.to_ascii_uppercase(), chars.as_str());
        }
    }
    
    result
}

#[allow(dead_code)]
fn is_primitive_type(type_name: &str) -> bool {
    matches!(type_name, 
        "bool" | "int8" | "int16" | "int32" | "int64" | 
        "uint16" | "uint32" | "uuid" | "float64" | 
        "string" | "bytes" | "records")
}

fn escape_rust_keyword(name: &str) -> String {
    // List of Rust keywords that need to be escaped with r# prefix
    const KEYWORDS: &[&str] = &[
        "as", "break", "const", "continue", "crate", "else", "enum", "extern",
        "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod",
        "move", "mut", "pub", "ref", "return", "self", "Self", "static", "struct",
        "super", "trait", "true", "type", "unsafe", "use", "where", "while",
        "async", "await", "dyn", "abstract", "become", "box", "do", "final",
        "macro", "override", "priv", "typeof", "unsized", "virtual", "yield",
        "try", "union",
    ];
    
    if KEYWORDS.contains(&name) {
        format!("r#{}", name)
    } else {
        name.to_string()
    }
}

/// Generate read code for a specific field type
fn generate_field_read(field_name: &str, field_type: &str) -> String {
    let mut output = String::new();
    
    // Handle array types
    if field_type.starts_with("[]") {
        let element_type = &field_type[2..];
        output.push_str(&format!("        // Read array of {} for field {}\n", element_type, field_name));
        output.push_str("        {\n");
        output.push_str("            let length = readable.read_int()?;\n");
        output.push_str("            if length < 0 {\n");
        output.push_str("                return Err(std::io::Error::new(std::io::ErrorKind::InvalidData, \"Negative array length\"));\n");
        output.push_str("            }\n");
        output.push_str(&format!("            result.{} = Vec::with_capacity(length as usize);\n", field_name));
        output.push_str("            for _ in 0..length {\n");
        output.push_str(&generate_array_element_read(element_type, field_name));
        output.push_str("            }\n");
        output.push_str("        }\n");
        return output;
    }
    
    // Handle primitive types
    match field_type {
        "bool" => {
            output.push_str(&format!("        result.{} = readable.read_byte()? != 0;\n", field_name));
        }
        "int8" => {
            output.push_str(&format!("        result.{} = readable.read_byte()? as i8;\n", field_name));
        }
        "int16" => {
            output.push_str(&format!("        result.{} = readable.read_short()?;\n", field_name));
        }
        "int32" => {
            output.push_str(&format!("        result.{} = readable.read_int()?;\n", field_name));
        }
        "int64" => {
            output.push_str(&format!("        result.{} = readable.read_long()?;\n", field_name));
        }
        "uint16" => {
            output.push_str(&format!("        result.{} = readable.read_unsigned_short()?;\n", field_name));
        }
        "uint32" => {
            output.push_str(&format!("        result.{} = readable.read_unsigned_int()?;\n", field_name));
        }
        "uuid" => {
            output.push_str(&format!("        result.{} = readable.read_uuid()?;\n", field_name));
        }
        "float64" => {
            output.push_str(&format!("        result.{} = readable.read_double()?;\n", field_name));
        }
        "string" => {
            output.push_str(&format!("        // Read string with length prefix for field {}\n", field_name));
            output.push_str("        {\n");
            output.push_str("            let length = readable.read_short()?;\n");
            output.push_str("            if length < 0 {\n");
            output.push_str("                return Err(std::io::Error::new(std::io::ErrorKind::InvalidData, \"Negative string length\"));\n");
            output.push_str("            }\n");
            output.push_str("            let mut bytes = vec![0u8; length as usize];\n");
            output.push_str("            readable.read_bytes(&mut bytes)?;\n");
            output.push_str(&format!("            result.{} = String::from_utf8(bytes)\n", field_name));
            output.push_str("                .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;\n");
            output.push_str("        }\n");
        }
        "bytes" | "records" => {
            output.push_str(&format!("        // Read bytes with length prefix for field {}\n", field_name));
            output.push_str("        {\n");
            output.push_str("            let length = readable.read_int()?;\n");
            output.push_str("            if length < 0 {\n");
            output.push_str(&format!("                result.{} = Vec::new();\n", field_name));
            output.push_str("            } else {\n");
            output.push_str("                let mut bytes = vec![0u8; length as usize];\n");
            output.push_str("                readable.read_bytes(&mut bytes)?;\n");
            output.push_str(&format!("                result.{} = bytes;\n", field_name));
            output.push_str("            }\n");
            output.push_str("        }\n");
        }
        _ => {
            // Struct types - capitalize first letter for struct name
            let struct_type = to_pascal_case(field_type);
            output.push_str(&format!("        result.{} = {}::read(readable, version)?;\n", field_name, struct_type));
        }
    }
    
    output
}

/// Generate read code for array element
fn generate_array_element_read(element_type: &str, field_name: &str) -> String {
    let mut output = String::new();
    
    match element_type {
        "bool" => {
            output.push_str(&format!("                result.{}.push(readable.read_byte()? != 0);\n", field_name));
        }
        "int8" => {
            output.push_str(&format!("                result.{}.push(readable.read_byte()? as i8);\n", field_name));
        }
        "int16" => {
            output.push_str(&format!("                result.{}.push(readable.read_short()?);\n", field_name));
        }
        "int32" => {
            output.push_str(&format!("                result.{}.push(readable.read_int()?);\n", field_name));
        }
        "int64" => {
            output.push_str(&format!("                result.{}.push(readable.read_long()?);\n", field_name));
        }
        "uint16" => {
            output.push_str(&format!("                result.{}.push(readable.read_unsigned_short()?);\n", field_name));
        }
        "uint32" => {
            output.push_str(&format!("                result.{}.push(readable.read_unsigned_int()?);\n", field_name));
        }
        "uuid" => {
            output.push_str(&format!("                result.{}.push(readable.read_uuid()?);\n", field_name));
        }
        "float64" => {
            output.push_str(&format!("                result.{}.push(readable.read_double()?);\n", field_name));
        }
        "string" => {
            output.push_str("                {\n");
            output.push_str("                    let length = readable.read_short()?;\n");
            output.push_str("                    if length < 0 {\n");
            output.push_str("                        return Err(std::io::Error::new(std::io::ErrorKind::InvalidData, \"Negative string length\"));\n");
            output.push_str("                    }\n");
            output.push_str("                    let mut bytes = vec![0u8; length as usize];\n");
            output.push_str("                    readable.read_bytes(&mut bytes)?;\n");
            output.push_str(&format!("                    result.{}.push(String::from_utf8(bytes)\n", field_name));
            output.push_str("                        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?);\n");
            output.push_str("                }\n");
        }
        "bytes" | "records" => {
            output.push_str("                {\n");
            output.push_str("                    let length = readable.read_int()?;\n");
            output.push_str("                    if length < 0 {\n");
            output.push_str(&format!("                        result.{}.push(Vec::new());\n", field_name));
            output.push_str("                    } else {\n");
            output.push_str("                        let mut bytes = vec![0u8; length as usize];\n");
            output.push_str("                        readable.read_bytes(&mut bytes)?;\n");
            output.push_str(&format!("                        result.{}.push(bytes);\n", field_name));
            output.push_str("                    }\n");
            output.push_str("                }\n");
        }
        _ => {
            // Nested struct in array
            let struct_type = to_pascal_case(element_type);
            output.push_str(&format!("                result.{}.push({}::read(readable, version)?);\n", field_name, struct_type));
        }
    }
    
    output
}

/// Generate write code for a specific field type
fn generate_field_write(field_name: &str, field_type: &str) -> String {
    let mut output = String::new();
    
    // Handle array types
    if field_type.starts_with("[]") {
        let element_type = &field_type[2..];
        output.push_str(&format!("        // Write array of {} for field {}\n", element_type, field_name));
        output.push_str(&format!("        writable.write_int(self.{}.len() as i32)?;\n", field_name));
        output.push_str(&format!("        for element in &self.{} {{\n", field_name));
        output.push_str(&generate_array_element_write(element_type));
        output.push_str("        }\n");
        return output;
    }
    
    // Handle primitive types
    match field_type {
        "bool" => {
            output.push_str(&format!("        writable.write_byte(if self.{} {{ 1 }} else {{ 0 }})?;\n", field_name));
        }
        "int8" => {
            output.push_str(&format!("        writable.write_byte(self.{})?;\n", field_name));
        }
        "int16" => {
            output.push_str(&format!("        writable.write_short(self.{})?;\n", field_name));
        }
        "int32" => {
            output.push_str(&format!("        writable.write_int(self.{})?;\n", field_name));
        }
        "int64" => {
            output.push_str(&format!("        writable.write_long(self.{})?;\n", field_name));
        }
        "uint16" => {
            output.push_str(&format!("        writable.write_unsigned_short(self.{})?;\n", field_name));
        }
        "uint32" => {
            output.push_str(&format!("        writable.write_unsigned_int(self.{})?;\n", field_name));
        }
        "uuid" => {
            output.push_str(&format!("        writable.write_uuid(&self.{})?;\n", field_name));
        }
        "float64" => {
            output.push_str(&format!("        writable.write_double(self.{})?;\n", field_name));
        }
        "string" => {
            output.push_str(&format!("        // Write string with length prefix for field {}\n", field_name));
            output.push_str("        {\n");
            output.push_str(&format!("            let bytes = self.{}.as_bytes();\n", field_name));
            output.push_str("            writable.write_short(bytes.len() as i16)?;\n");
            output.push_str("            writable.write_bytes(bytes)?;\n");
            output.push_str("        }\n");
        }
        "bytes" | "records" => {
            output.push_str(&format!("        // Write bytes with length prefix for field {}\n", field_name));
            output.push_str(&format!("        writable.write_int(self.{}.len() as i32)?;\n", field_name));
            output.push_str(&format!("        writable.write_bytes(&self.{})?;\n", field_name));
        }
        _ => {
            // Struct types
            output.push_str(&format!("        self.{}.write(writable, version)?;\n", field_name));
        }
    }
    
    output
}

/// Generate write code for array element
fn generate_array_element_write(element_type: &str) -> String {
    let mut output = String::new();
    
    match element_type {
        "bool" => {
            output.push_str("            writable.write_byte(if *element { 1 } else { 0 })?;\n");
        }
        "int8" => {
            output.push_str("            writable.write_byte(*element)?;\n");
        }
        "int16" => {
            output.push_str("            writable.write_short(*element)?;\n");
        }
        "int32" => {
            output.push_str("            writable.write_int(*element)?;\n");
        }
        "int64" => {
            output.push_str("            writable.write_long(*element)?;\n");
        }
        "uint16" => {
            output.push_str("            writable.write_unsigned_short(*element)?;\n");
        }
        "uint32" => {
            output.push_str("            writable.write_unsigned_int(*element)?;\n");
        }
        "uuid" => {
            output.push_str("            writable.write_uuid(element)?;\n");
        }
        "float64" => {
            output.push_str("            writable.write_double(*element)?;\n");
        }
        "string" => {
            output.push_str("            {\n");
            output.push_str("                let bytes = element.as_bytes();\n");
            output.push_str("                writable.write_short(bytes.len() as i16)?;\n");
            output.push_str("                writable.write_bytes(bytes)?;\n");
            output.push_str("            }\n");
        }
        "bytes" | "records" => {
            output.push_str("            writable.write_int(element.len() as i32)?;\n");
            output.push_str("            writable.write_bytes(element)?;\n");
        }
        _ => {
            // Nested struct in array
            output.push_str("            element.write(writable, version)?;\n");
        }
    }
    
    output
}

