# Copyright 2025 Confluent Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Every generated error class: (defining module, class name, Java class).

GENERATED, DO NOT EDIT. Produced from the Java source by
``cargo xtask generate-error-codes`` (CLAUDE.md, Python Binding Conventions,
Errors) and validated for staleness by ``cargo xtask check-generated``.
"""

from __future__ import annotations

ERRORS: tuple[tuple[str, str, str], ...] = (
    ("confluent_kafka.common.config.config_error", "ConfigError", "org.apache.kafka.common.config.ConfigException"),
    ("confluent_kafka.common.errors.api_error", "ApiError", "org.apache.kafka.common.errors.ApiException"),
    ("confluent_kafka.common.errors.application_recoverable_error", "ApplicationRecoverableError", "org.apache.kafka.common.errors.ApplicationRecoverableException"),
    ("confluent_kafka.common.errors.authentication_error", "AuthenticationError", "org.apache.kafka.common.errors.AuthenticationException"),
    ("confluent_kafka.common.errors.authorization_error", "AuthorizationError", "org.apache.kafka.common.errors.AuthorizationException"),
    ("confluent_kafka.common.errors.authorizer_not_ready_error", "AuthorizerNotReadyError", "org.apache.kafka.common.errors.AuthorizerNotReadyException"),
    ("confluent_kafka.common.errors.broker_id_not_registered_error", "BrokerIdNotRegisteredError", "org.apache.kafka.common.errors.BrokerIdNotRegisteredException"),
    ("confluent_kafka.common.errors.broker_not_available_error", "BrokerNotAvailableError", "org.apache.kafka.common.errors.BrokerNotAvailableException"),
    ("confluent_kafka.common.errors.cluster_authorization_error", "ClusterAuthorizationError", "org.apache.kafka.common.errors.ClusterAuthorizationException"),
    ("confluent_kafka.common.errors.concurrent_transactions_error", "ConcurrentTransactionsError", "org.apache.kafka.common.errors.ConcurrentTransactionsException"),
    ("confluent_kafka.common.errors.controller_moved_error", "ControllerMovedError", "org.apache.kafka.common.errors.ControllerMovedException"),
    ("confluent_kafka.common.errors.coordinator_load_in_progress_error", "CoordinatorLoadInProgressError", "org.apache.kafka.common.errors.CoordinatorLoadInProgressException"),
    ("confluent_kafka.common.errors.coordinator_not_available_error", "CoordinatorNotAvailableError", "org.apache.kafka.common.errors.CoordinatorNotAvailableException"),
    ("confluent_kafka.common.errors.corrupt_record_error", "CorruptRecordError", "org.apache.kafka.common.errors.CorruptRecordException"),
    ("confluent_kafka.common.errors.delegation_token_authorization_error", "DelegationTokenAuthorizationError", "org.apache.kafka.common.errors.DelegationTokenAuthorizationException"),
    ("confluent_kafka.common.errors.delegation_token_disabled_error", "DelegationTokenDisabledError", "org.apache.kafka.common.errors.DelegationTokenDisabledException"),
    ("confluent_kafka.common.errors.delegation_token_expired_error", "DelegationTokenExpiredError", "org.apache.kafka.common.errors.DelegationTokenExpiredException"),
    ("confluent_kafka.common.errors.delegation_token_not_found_error", "DelegationTokenNotFoundError", "org.apache.kafka.common.errors.DelegationTokenNotFoundException"),
    ("confluent_kafka.common.errors.delegation_token_owner_mismatch_error", "DelegationTokenOwnerMismatchError", "org.apache.kafka.common.errors.DelegationTokenOwnerMismatchException"),
    ("confluent_kafka.common.errors.disconnect_error", "DisconnectError", "org.apache.kafka.common.errors.DisconnectException"),
    ("confluent_kafka.common.errors.duplicate_broker_registration_error", "DuplicateBrokerRegistrationError", "org.apache.kafka.common.errors.DuplicateBrokerRegistrationException"),
    ("confluent_kafka.common.errors.duplicate_resource_error", "DuplicateResourceError", "org.apache.kafka.common.errors.DuplicateResourceException"),
    ("confluent_kafka.common.errors.duplicate_sequence_error", "DuplicateSequenceError", "org.apache.kafka.common.errors.DuplicateSequenceException"),
    ("confluent_kafka.common.errors.duplicate_voter_error", "DuplicateVoterError", "org.apache.kafka.common.errors.DuplicateVoterException"),
    ("confluent_kafka.common.errors.election_not_needed_error", "ElectionNotNeededError", "org.apache.kafka.common.errors.ElectionNotNeededException"),
    ("confluent_kafka.common.errors.eligible_leaders_not_available_error", "EligibleLeadersNotAvailableError", "org.apache.kafka.common.errors.EligibleLeadersNotAvailableException"),
    ("confluent_kafka.common.errors.feature_update_failed_error", "FeatureUpdateFailedError", "org.apache.kafka.common.errors.FeatureUpdateFailedException"),
    ("confluent_kafka.common.errors.fenced_instance_id_error", "FencedInstanceIdError", "org.apache.kafka.common.errors.FencedInstanceIdException"),
    ("confluent_kafka.common.errors.fenced_leader_epoch_error", "FencedLeaderEpochError", "org.apache.kafka.common.errors.FencedLeaderEpochException"),
    ("confluent_kafka.common.errors.fenced_member_epoch_error", "FencedMemberEpochError", "org.apache.kafka.common.errors.FencedMemberEpochException"),
    ("confluent_kafka.common.errors.fenced_state_epoch_error", "FencedStateEpochError", "org.apache.kafka.common.errors.FencedStateEpochException"),
    ("confluent_kafka.common.errors.fetch_session_id_not_found_error", "FetchSessionIdNotFoundError", "org.apache.kafka.common.errors.FetchSessionIdNotFoundException"),
    ("confluent_kafka.common.errors.fetch_session_topic_id_error", "FetchSessionTopicIdError", "org.apache.kafka.common.errors.FetchSessionTopicIdException"),
    ("confluent_kafka.common.errors.group_authorization_error", "GroupAuthorizationError", "org.apache.kafka.common.errors.GroupAuthorizationException"),
    ("confluent_kafka.common.errors.group_id_not_found_error", "GroupIdNotFoundError", "org.apache.kafka.common.errors.GroupIdNotFoundException"),
    ("confluent_kafka.common.errors.group_max_size_reached_error", "GroupMaxSizeReachedError", "org.apache.kafka.common.errors.GroupMaxSizeReachedException"),
    ("confluent_kafka.common.errors.group_not_empty_error", "GroupNotEmptyError", "org.apache.kafka.common.errors.GroupNotEmptyException"),
    ("confluent_kafka.common.errors.group_subscribed_to_topic_error", "GroupSubscribedToTopicError", "org.apache.kafka.common.errors.GroupSubscribedToTopicException"),
    ("confluent_kafka.common.errors.illegal_generation_error", "IllegalGenerationError", "org.apache.kafka.common.errors.IllegalGenerationException"),
    ("confluent_kafka.common.errors.illegal_sasl_state_error", "IllegalSaslStateError", "org.apache.kafka.common.errors.IllegalSaslStateException"),
    ("confluent_kafka.common.errors.inconsistent_cluster_id_error", "InconsistentClusterIdError", "org.apache.kafka.common.errors.InconsistentClusterIdException"),
    ("confluent_kafka.common.errors.inconsistent_group_protocol_error", "InconsistentGroupProtocolError", "org.apache.kafka.common.errors.InconsistentGroupProtocolException"),
    ("confluent_kafka.common.errors.inconsistent_topic_id_error", "InconsistentTopicIdError", "org.apache.kafka.common.errors.InconsistentTopicIdException"),
    ("confluent_kafka.common.errors.inconsistent_voter_set_error", "InconsistentVoterSetError", "org.apache.kafka.common.errors.InconsistentVoterSetException"),
    ("confluent_kafka.common.errors.ineligible_replica_error", "IneligibleReplicaError", "org.apache.kafka.common.errors.IneligibleReplicaException"),
    ("confluent_kafka.common.errors.interrupt_error", "InterruptError", "org.apache.kafka.common.errors.InterruptException"),
    ("confluent_kafka.common.errors.invalid_commit_offset_size_error", "InvalidCommitOffsetSizeError", "org.apache.kafka.common.errors.InvalidCommitOffsetSizeException"),
    ("confluent_kafka.common.errors.invalid_configuration_error", "InvalidConfigurationError", "org.apache.kafka.common.errors.InvalidConfigurationException"),
    ("confluent_kafka.common.errors.invalid_fetch_session_epoch_error", "InvalidFetchSessionEpochError", "org.apache.kafka.common.errors.InvalidFetchSessionEpochException"),
    ("confluent_kafka.common.errors.invalid_fetch_size_error", "InvalidFetchSizeError", "org.apache.kafka.common.errors.InvalidFetchSizeException"),
    ("confluent_kafka.common.errors.invalid_group_id_error", "InvalidGroupIdError", "org.apache.kafka.common.errors.InvalidGroupIdException"),
    ("confluent_kafka.common.errors.invalid_metadata_error", "InvalidMetadataError", "org.apache.kafka.common.errors.InvalidMetadataException"),
    ("confluent_kafka.common.errors.invalid_offset_error", "InvalidOffsetError", "org.apache.kafka.common.errors.InvalidOffsetException"),
    ("confluent_kafka.common.errors.invalid_partitions_error", "InvalidPartitionsError", "org.apache.kafka.common.errors.InvalidPartitionsException"),
    ("confluent_kafka.common.errors.invalid_pid_mapping_error", "InvalidPidMappingError", "org.apache.kafka.common.errors.InvalidPidMappingException"),
    ("confluent_kafka.common.errors.invalid_principal_type_error", "InvalidPrincipalTypeError", "org.apache.kafka.common.errors.InvalidPrincipalTypeException"),
    ("confluent_kafka.common.errors.invalid_producer_epoch_error", "InvalidProducerEpochError", "org.apache.kafka.common.errors.InvalidProducerEpochException"),
    ("confluent_kafka.common.errors.invalid_record_state_error", "InvalidRecordStateError", "org.apache.kafka.common.errors.InvalidRecordStateException"),
    ("confluent_kafka.common.errors.invalid_registration_error", "InvalidRegistrationError", "org.apache.kafka.common.errors.InvalidRegistrationException"),
    ("confluent_kafka.common.errors.invalid_regular_expression_error", "InvalidRegularExpressionError", "org.apache.kafka.common.errors.InvalidRegularExpression"),
    ("confluent_kafka.common.errors.invalid_replica_assignment_error", "InvalidReplicaAssignmentError", "org.apache.kafka.common.errors.InvalidReplicaAssignmentException"),
    ("confluent_kafka.common.errors.invalid_replication_factor_error", "InvalidReplicationFactorError", "org.apache.kafka.common.errors.InvalidReplicationFactorException"),
    ("confluent_kafka.common.errors.invalid_request_error", "InvalidRequestError", "org.apache.kafka.common.errors.InvalidRequestException"),
    ("confluent_kafka.common.errors.invalid_required_acks_error", "InvalidRequiredAcksError", "org.apache.kafka.common.errors.InvalidRequiredAcksException"),
    ("confluent_kafka.common.errors.invalid_session_timeout_error", "InvalidSessionTimeoutError", "org.apache.kafka.common.errors.InvalidSessionTimeoutException"),
    ("confluent_kafka.common.errors.invalid_share_session_epoch_error", "InvalidShareSessionEpochError", "org.apache.kafka.common.errors.InvalidShareSessionEpochException"),
    ("confluent_kafka.common.errors.invalid_timestamp_error", "InvalidTimestampError", "org.apache.kafka.common.errors.InvalidTimestampException"),
    ("confluent_kafka.common.errors.invalid_topic_error", "InvalidTopicError", "org.apache.kafka.common.errors.InvalidTopicException"),
    ("confluent_kafka.common.errors.invalid_txn_state_error", "InvalidTxnStateError", "org.apache.kafka.common.errors.InvalidTxnStateException"),
    ("confluent_kafka.common.errors.invalid_txn_timeout_error", "InvalidTxnTimeoutError", "org.apache.kafka.common.errors.InvalidTxnTimeoutException"),
    ("confluent_kafka.common.errors.invalid_update_version_error", "InvalidUpdateVersionError", "org.apache.kafka.common.errors.InvalidUpdateVersionException"),
    ("confluent_kafka.common.errors.invalid_voter_key_error", "InvalidVoterKeyError", "org.apache.kafka.common.errors.InvalidVoterKeyException"),
    ("confluent_kafka.common.errors.kafka_storage_error", "KafkaStorageError", "org.apache.kafka.common.errors.KafkaStorageException"),
    ("confluent_kafka.common.errors.leader_not_available_error", "LeaderNotAvailableError", "org.apache.kafka.common.errors.LeaderNotAvailableException"),
    ("confluent_kafka.common.errors.listener_not_found_error", "ListenerNotFoundError", "org.apache.kafka.common.errors.ListenerNotFoundException"),
    ("confluent_kafka.common.errors.log_dir_not_found_error", "LogDirNotFoundError", "org.apache.kafka.common.errors.LogDirNotFoundException"),
    ("confluent_kafka.common.errors.member_id_required_error", "MemberIdRequiredError", "org.apache.kafka.common.errors.MemberIdRequiredException"),
    ("confluent_kafka.common.errors.mismatched_endpoint_type_error", "MismatchedEndpointTypeError", "org.apache.kafka.common.errors.MismatchedEndpointTypeException"),
    ("confluent_kafka.common.errors.network_error", "NetworkError", "org.apache.kafka.common.errors.NetworkException"),
    ("confluent_kafka.common.errors.new_leader_elected_error", "NewLeaderElectedError", "org.apache.kafka.common.errors.NewLeaderElectedException"),
    ("confluent_kafka.common.errors.no_reassignment_in_progress_error", "NoReassignmentInProgressError", "org.apache.kafka.common.errors.NoReassignmentInProgressException"),
    ("confluent_kafka.common.errors.not_controller_error", "NotControllerError", "org.apache.kafka.common.errors.NotControllerException"),
    ("confluent_kafka.common.errors.not_coordinator_error", "NotCoordinatorError", "org.apache.kafka.common.errors.NotCoordinatorException"),
    ("confluent_kafka.common.errors.not_enough_replicas_after_append_error", "NotEnoughReplicasAfterAppendError", "org.apache.kafka.common.errors.NotEnoughReplicasAfterAppendException"),
    ("confluent_kafka.common.errors.not_enough_replicas_error", "NotEnoughReplicasError", "org.apache.kafka.common.errors.NotEnoughReplicasException"),
    ("confluent_kafka.common.errors.not_leader_or_follower_error", "NotLeaderOrFollowerError", "org.apache.kafka.common.errors.NotLeaderOrFollowerException"),
    ("confluent_kafka.common.errors.offset_metadata_too_large_error", "OffsetMetadataTooLargeError", "org.apache.kafka.common.errors.OffsetMetadataTooLarge"),
    ("confluent_kafka.common.errors.offset_moved_to_tiered_storage_error", "OffsetMovedToTieredStorageError", "org.apache.kafka.common.errors.OffsetMovedToTieredStorageException"),
    ("confluent_kafka.common.errors.offset_not_available_error", "OffsetNotAvailableError", "org.apache.kafka.common.errors.OffsetNotAvailableException"),
    ("confluent_kafka.common.errors.offset_out_of_range_error", "OffsetOutOfRangeError", "org.apache.kafka.common.errors.OffsetOutOfRangeException"),
    ("confluent_kafka.common.errors.operation_not_attempted_error", "OperationNotAttemptedError", "org.apache.kafka.common.errors.OperationNotAttemptedException"),
    ("confluent_kafka.common.errors.out_of_order_sequence_error", "OutOfOrderSequenceError", "org.apache.kafka.common.errors.OutOfOrderSequenceException"),
    ("confluent_kafka.common.errors.policy_violation_error", "PolicyViolationError", "org.apache.kafka.common.errors.PolicyViolationException"),
    ("confluent_kafka.common.errors.position_out_of_range_error", "PositionOutOfRangeError", "org.apache.kafka.common.errors.PositionOutOfRangeException"),
    ("confluent_kafka.common.errors.preferred_leader_not_available_error", "PreferredLeaderNotAvailableError", "org.apache.kafka.common.errors.PreferredLeaderNotAvailableException"),
    ("confluent_kafka.common.errors.principal_deserialization_error", "PrincipalDeserializationError", "org.apache.kafka.common.errors.PrincipalDeserializationException"),
    ("confluent_kafka.common.errors.producer_fenced_error", "ProducerFencedError", "org.apache.kafka.common.errors.ProducerFencedException"),
    ("confluent_kafka.common.errors.reassignment_in_progress_error", "ReassignmentInProgressError", "org.apache.kafka.common.errors.ReassignmentInProgressException"),
    ("confluent_kafka.common.errors.rebalance_in_progress_error", "RebalanceInProgressError", "org.apache.kafka.common.errors.RebalanceInProgressException"),
    ("confluent_kafka.common.errors.rebootstrap_required_error", "RebootstrapRequiredError", "org.apache.kafka.common.errors.RebootstrapRequiredException"),
    ("confluent_kafka.common.errors.record_batch_too_large_error", "RecordBatchTooLargeError", "org.apache.kafka.common.errors.RecordBatchTooLargeException"),
    ("confluent_kafka.common.errors.record_deserialization_error", "RecordDeserializationError", "org.apache.kafka.common.errors.RecordDeserializationException"),
    ("confluent_kafka.common.errors.record_too_large_error", "RecordTooLargeError", "org.apache.kafka.common.errors.RecordTooLargeException"),
    ("confluent_kafka.common.errors.refresh_retriable_error", "RefreshRetriableError", "org.apache.kafka.common.errors.RefreshRetriableException"),
    ("confluent_kafka.common.errors.replica_not_available_error", "ReplicaNotAvailableError", "org.apache.kafka.common.errors.ReplicaNotAvailableException"),
    ("confluent_kafka.common.errors.resource_not_found_error", "ResourceNotFoundError", "org.apache.kafka.common.errors.ResourceNotFoundException"),
    ("confluent_kafka.common.errors.retriable_error", "RetriableError", "org.apache.kafka.common.errors.RetriableException"),
    ("confluent_kafka.common.errors.sasl_authentication_error", "SaslAuthenticationError", "org.apache.kafka.common.errors.SaslAuthenticationException"),
    ("confluent_kafka.common.errors.security_disabled_error", "SecurityDisabledError", "org.apache.kafka.common.errors.SecurityDisabledException"),
    ("confluent_kafka.common.errors.serialization_error", "SerializationError", "org.apache.kafka.common.errors.SerializationException"),
    ("confluent_kafka.common.errors.share_session_limit_reached_error", "ShareSessionLimitReachedError", "org.apache.kafka.common.errors.ShareSessionLimitReachedException"),
    ("confluent_kafka.common.errors.share_session_not_found_error", "ShareSessionNotFoundError", "org.apache.kafka.common.errors.ShareSessionNotFoundException"),
    ("confluent_kafka.common.errors.snapshot_not_found_error", "SnapshotNotFoundError", "org.apache.kafka.common.errors.SnapshotNotFoundException"),
    ("confluent_kafka.common.errors.ssl_authentication_error", "SslAuthenticationError", "org.apache.kafka.common.errors.SslAuthenticationException"),
    ("confluent_kafka.common.errors.stale_broker_epoch_error", "StaleBrokerEpochError", "org.apache.kafka.common.errors.StaleBrokerEpochException"),
    ("confluent_kafka.common.errors.stale_member_epoch_error", "StaleMemberEpochError", "org.apache.kafka.common.errors.StaleMemberEpochException"),
    ("confluent_kafka.common.errors.streams_invalid_topology_epoch_error", "StreamsInvalidTopologyEpochError", "org.apache.kafka.common.errors.StreamsInvalidTopologyEpochException"),
    ("confluent_kafka.common.errors.streams_invalid_topology_error", "StreamsInvalidTopologyError", "org.apache.kafka.common.errors.StreamsInvalidTopologyException"),
    ("confluent_kafka.common.errors.streams_topology_fenced_error", "StreamsTopologyFencedError", "org.apache.kafka.common.errors.StreamsTopologyFencedException"),
    ("confluent_kafka.common.errors.telemetry_too_large_error", "TelemetryTooLargeError", "org.apache.kafka.common.errors.TelemetryTooLargeException"),
    ("confluent_kafka.common.errors.throttling_quota_exceeded_error", "ThrottlingQuotaExceededError", "org.apache.kafka.common.errors.ThrottlingQuotaExceededException"),
    ("confluent_kafka.common.errors.timeout_error", "TimeoutError", "org.apache.kafka.common.errors.TimeoutException"),
    ("confluent_kafka.common.errors.topic_authorization_error", "TopicAuthorizationError", "org.apache.kafka.common.errors.TopicAuthorizationException"),
    ("confluent_kafka.common.errors.topic_deletion_disabled_error", "TopicDeletionDisabledError", "org.apache.kafka.common.errors.TopicDeletionDisabledException"),
    ("confluent_kafka.common.errors.topic_exists_error", "TopicExistsError", "org.apache.kafka.common.errors.TopicExistsException"),
    ("confluent_kafka.common.errors.transaction_abortable_error", "TransactionAbortableError", "org.apache.kafka.common.errors.TransactionAbortableException"),
    ("confluent_kafka.common.errors.transaction_aborted_error", "TransactionAbortedError", "org.apache.kafka.common.errors.TransactionAbortedException"),
    ("confluent_kafka.common.errors.transaction_coordinator_fenced_error", "TransactionCoordinatorFencedError", "org.apache.kafka.common.errors.TransactionCoordinatorFencedException"),
    ("confluent_kafka.common.errors.transactional_id_authorization_error", "TransactionalIdAuthorizationError", "org.apache.kafka.common.errors.TransactionalIdAuthorizationException"),
    ("confluent_kafka.common.errors.transactional_id_not_found_error", "TransactionalIdNotFoundError", "org.apache.kafka.common.errors.TransactionalIdNotFoundException"),
    ("confluent_kafka.common.errors.unacceptable_credential_error", "UnacceptableCredentialError", "org.apache.kafka.common.errors.UnacceptableCredentialException"),
    ("confluent_kafka.common.errors.unknown_controller_id_error", "UnknownControllerIdError", "org.apache.kafka.common.errors.UnknownControllerIdException"),
    ("confluent_kafka.common.errors.unknown_leader_epoch_error", "UnknownLeaderEpochError", "org.apache.kafka.common.errors.UnknownLeaderEpochException"),
    ("confluent_kafka.common.errors.unknown_member_id_error", "UnknownMemberIdError", "org.apache.kafka.common.errors.UnknownMemberIdException"),
    ("confluent_kafka.common.errors.unknown_producer_id_error", "UnknownProducerIdError", "org.apache.kafka.common.errors.UnknownProducerIdException"),
    ("confluent_kafka.common.errors.unknown_server_error", "UnknownServerError", "org.apache.kafka.common.errors.UnknownServerException"),
    ("confluent_kafka.common.errors.unknown_subscription_id_error", "UnknownSubscriptionIdError", "org.apache.kafka.common.errors.UnknownSubscriptionIdException"),
    ("confluent_kafka.common.errors.unknown_topic_id_error", "UnknownTopicIdError", "org.apache.kafka.common.errors.UnknownTopicIdException"),
    ("confluent_kafka.common.errors.unknown_topic_or_partition_error", "UnknownTopicOrPartitionError", "org.apache.kafka.common.errors.UnknownTopicOrPartitionException"),
    ("confluent_kafka.common.errors.unreleased_instance_id_error", "UnreleasedInstanceIdError", "org.apache.kafka.common.errors.UnreleasedInstanceIdException"),
    ("confluent_kafka.common.errors.unstable_offset_commit_error", "UnstableOffsetCommitError", "org.apache.kafka.common.errors.UnstableOffsetCommitException"),
    ("confluent_kafka.common.errors.unsupported_assignor_error", "UnsupportedAssignorError", "org.apache.kafka.common.errors.UnsupportedAssignorException"),
    ("confluent_kafka.common.errors.unsupported_by_authentication_error", "UnsupportedByAuthenticationError", "org.apache.kafka.common.errors.UnsupportedByAuthenticationException"),
    ("confluent_kafka.common.errors.unsupported_compression_type_error", "UnsupportedCompressionTypeError", "org.apache.kafka.common.errors.UnsupportedCompressionTypeException"),
    ("confluent_kafka.common.errors.unsupported_endpoint_type_error", "UnsupportedEndpointTypeError", "org.apache.kafka.common.errors.UnsupportedEndpointTypeException"),
    ("confluent_kafka.common.errors.unsupported_for_message_format_error", "UnsupportedForMessageFormatError", "org.apache.kafka.common.errors.UnsupportedForMessageFormatException"),
    ("confluent_kafka.common.errors.unsupported_sasl_mechanism_error", "UnsupportedSaslMechanismError", "org.apache.kafka.common.errors.UnsupportedSaslMechanismException"),
    ("confluent_kafka.common.errors.unsupported_version_error", "UnsupportedVersionError", "org.apache.kafka.common.errors.UnsupportedVersionException"),
    ("confluent_kafka.common.errors.voter_not_found_error", "VoterNotFoundError", "org.apache.kafka.common.errors.VoterNotFoundException"),
    ("confluent_kafka.common.errors.wakeup_error", "WakeupError", "org.apache.kafka.common.errors.WakeupException"),
    ("confluent_kafka.common.invalid_record_error", "InvalidRecordError", "org.apache.kafka.common.InvalidRecordException"),
    ("confluent_kafka.common.kafka_error", "KafkaError", "org.apache.kafka.common.KafkaException"),
    ("confluent_kafka.common.metrics.quota_violation_error", "QuotaViolationError", "org.apache.kafka.common.metrics.QuotaViolationException"),
    ("confluent_kafka.common.network.invalid_receive_error", "InvalidReceiveError", "org.apache.kafka.common.network.InvalidReceiveException"),
    ("confluent_kafka.common.protocol.types.schema_error", "SchemaError", "org.apache.kafka.common.protocol.types.SchemaException"),
    ("confluent_kafka.common.requests.correlation_id_mismatch_error", "CorrelationIdMismatchError", "org.apache.kafka.common.requests.CorrelationIdMismatchException"),
    ("confluent_kafka.concurrent_modification_error", "ConcurrentModificationError", "java.util.ConcurrentModificationException"),
    ("confluent_kafka.consumer.commit_failed_error", "CommitFailedError", "org.apache.kafka.clients.consumer.CommitFailedException"),
    ("confluent_kafka.consumer.invalid_offset_error", "InvalidOffsetError", "org.apache.kafka.clients.consumer.InvalidOffsetException"),
    ("confluent_kafka.consumer.log_truncation_error", "LogTruncationError", "org.apache.kafka.clients.consumer.LogTruncationException"),
    ("confluent_kafka.consumer.no_offset_for_partition_error", "NoOffsetForPartitionError", "org.apache.kafka.clients.consumer.NoOffsetForPartitionException"),
    ("confluent_kafka.consumer.offset_out_of_range_error", "OffsetOutOfRangeError", "org.apache.kafka.clients.consumer.OffsetOutOfRangeException"),
    ("confluent_kafka.consumer.retriable_commit_failed_error", "RetriableCommitFailedError", "org.apache.kafka.clients.consumer.RetriableCommitFailedException"),
    ("confluent_kafka.illegal_argument_error", "IllegalArgumentError", "java.lang.IllegalArgumentException"),
    ("confluent_kafka.illegal_state_error", "IllegalStateError", "java.lang.IllegalStateException"),
    ("confluent_kafka.no_such_element_error", "NoSuchElementError", "java.util.NoSuchElementException"),
    ("confluent_kafka.null_pointer_error", "NullPointerError", "java.lang.NullPointerException"),
    ("confluent_kafka.producer.buffer_exhausted_error", "BufferExhaustedError", "org.apache.kafka.clients.producer.BufferExhaustedException"),
    ("confluent_kafka.timeout_error", "TimeoutError", "java.util.concurrent.TimeoutException"),
)
