// Copyright 2025 Confluent Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! `ConsumerGroupHeartbeat` request handling.
//!
//! Corresponds to `org.apache.kafka.common.requests.ConsumerGroupHeartbeatRequest`.

use std::io;

use crate::common::protocol::{ApiKeys, Errors, Readable};
use crate::consumer_group_heartbeat_request_data::ConsumerGroupHeartbeatRequestData;
use crate::consumer_group_heartbeat_response_data::ConsumerGroupHeartbeatResponseData;

use super::ConcreteRequest;
use super::ConcreteResponse;
use super::ConsumerGroupHeartbeatResponse;
use super::RequestBuilder;

/// A member epoch of `-1` means that the member wants to leave the group.
///
/// Corresponds to `ConsumerGroupHeartbeatRequest.LEAVE_GROUP_MEMBER_EPOCH`.
pub const LEAVE_GROUP_MEMBER_EPOCH: i32 = -1;

/// A member epoch of `-2` means that a static member wants to leave the group.
///
/// Corresponds to `ConsumerGroupHeartbeatRequest.LEAVE_GROUP_STATIC_MEMBER_EPOCH`.
pub const LEAVE_GROUP_STATIC_MEMBER_EPOCH: i32 = -2;

/// A member epoch of `0` means that the member wants to join the group.
///
/// Corresponds to `ConsumerGroupHeartbeatRequest.JOIN_GROUP_MEMBER_EPOCH`.
pub const JOIN_GROUP_MEMBER_EPOCH: i32 = 0;

/// The version from which consumers are required to generate their own member id.
///
/// Starting from this version, member id must be generated by the consumer instance
/// instead of being provided by the server.
///
/// Corresponds to `ConsumerGroupHeartbeatRequest.CONSUMER_GENERATED_MEMBER_ID_REQUIRED_VERSION`.
pub const CONSUMER_GENERATED_MEMBER_ID_REQUIRED_VERSION: i16 = 1;

/// Error message for regex resolution not supported on v0.
///
/// Corresponds to `ConsumerGroupHeartbeatRequest.REGEX_RESOLUTION_NOT_SUPPORTED_MSG`.
pub const REGEX_RESOLUTION_NOT_SUPPORTED_MSG: &str = "The cluster does not support regular expressions resolution on ConsumerGroupHeartbeat API \
     version 0. It must be upgraded to use ConsumerGroupHeartbeat API version >= 1 to allow to \
     subscribe to a SubscriptionPattern.";

/// A `ConsumerGroupHeartbeat` request.
///
/// Corresponds to `org.apache.kafka.common.requests.ConsumerGroupHeartbeatRequest`.
#[derive(Debug, Clone)]
pub struct ConsumerGroupHeartbeatRequest {
    data: ConsumerGroupHeartbeatRequestData,
    version: i16,
}

impl ConsumerGroupHeartbeatRequest {
    /// Creates a new `ConsumerGroupHeartbeatRequest` from data and version.
    pub fn new(data: ConsumerGroupHeartbeatRequestData, version: i16) -> Self {
        Self { data, version }
    }

    /// Returns a reference to the underlying data.
    pub fn data(&self) -> &ConsumerGroupHeartbeatRequestData {
        &self.data
    }

    /// Returns the API version of this request.
    pub fn version(&self) -> i16 {
        self.version
    }

    /// Returns the API key for this request.
    pub fn api_key(&self) -> &'static ApiKeys {
        &ApiKeys::CONSUMER_GROUP_HEARTBEAT
    }

    /// Builds the canonical error response for this request, matching Java's
    /// `ConsumerGroupHeartbeatRequest.getErrorResponse(throttleTimeMs, Throwable)`.
    pub fn get_error_response(&self, throttle_time_ms: i32, error: &Errors) -> ConcreteResponse {
        let mut response = ConsumerGroupHeartbeatResponseData::new();
        response.set_throttle_time_ms(throttle_time_ms).set_error_code(error.code());
        ConcreteResponse::ConsumerGroupHeartbeat(ConsumerGroupHeartbeatResponse::new(response))
    }

    /// Parses a `ConsumerGroupHeartbeatRequest` from a readable buffer at the given
    /// version.
    ///
    /// # Errors
    ///
    /// Returns an error if parsing fails.
    pub fn parse(readable: &mut dyn Readable, version: i16) -> io::Result<Self> {
        let data = ConsumerGroupHeartbeatRequestData::read(readable, version)?;
        Ok(Self::new(data, version))
    }
}

impl std::fmt::Display for ConsumerGroupHeartbeatRequest {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "ConsumerGroupHeartbeatRequest(version={}, data={})", self.version, self.data)
    }
}

/// Builder for [`ConsumerGroupHeartbeatRequest`].
///
/// Corresponds to `ConsumerGroupHeartbeatRequest.Builder` in Java.
#[derive(Debug, Clone)]
pub struct ConsumerGroupHeartbeatRequestBuilder {
    data: ConsumerGroupHeartbeatRequestData,
    oldest_allowed_version: i16,
    latest_allowed_version: i16,
}

impl ConsumerGroupHeartbeatRequestBuilder {
    /// Creates a builder wrapping the given data with the full supported
    /// version range.
    pub fn new(data: ConsumerGroupHeartbeatRequestData) -> Self {
        Self {
            data,
            oldest_allowed_version: ApiKeys::CONSUMER_GROUP_HEARTBEAT.oldest_version(),
            latest_allowed_version: ApiKeys::CONSUMER_GROUP_HEARTBEAT.latest_version(),
        }
    }

    /// Returns a reference to the underlying data.
    pub fn data(&self) -> &ConsumerGroupHeartbeatRequestData {
        &self.data
    }
}

impl RequestBuilder for ConsumerGroupHeartbeatRequestBuilder {
    fn api_key(&self) -> &'static ApiKeys {
        &ApiKeys::CONSUMER_GROUP_HEARTBEAT
    }

    fn oldest_allowed_version(&self) -> i16 {
        self.oldest_allowed_version
    }

    fn latest_allowed_version(&self) -> i16 {
        self.latest_allowed_version
    }

    fn build_version(&self, version: i16) -> io::Result<ConcreteRequest> {
        // Mirrors `ConsumerGroupHeartbeatRequest.Builder.build(short version)`.
        if version == 0 && self.data.subscribed_topic_regex.is_some() {
            return Err(io::Error::new(io::ErrorKind::Unsupported, REGEX_RESOLUTION_NOT_SUPPORTED_MSG));
        }
        Ok(ConcreteRequest::ConsumerGroupHeartbeat(ConsumerGroupHeartbeatRequest::new(
            self.data.clone(),
            version,
        )))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Verifies the API key accessor.
    #[test]
    fn test_api_key() {
        let builder = ConsumerGroupHeartbeatRequestBuilder::new(ConsumerGroupHeartbeatRequestData::new());
        assert_eq!(builder.api_key(), &ApiKeys::CONSUMER_GROUP_HEARTBEAT);
    }

    /// Verifies that v0 with a regex pattern is rejected, mirroring Java's
    /// `Builder.build` check.
    #[test]
    fn test_v0_regex_rejected() {
        let mut data = ConsumerGroupHeartbeatRequestData::new();
        data.set_subscribed_topic_regex(Some("topic-.*".to_string()));
        let builder = ConsumerGroupHeartbeatRequestBuilder::new(data);
        let err = builder.build_version(0).expect_err("v0 with regex must be rejected");
        assert!(err.to_string().contains("regular expressions"), "got: {err}");
    }

    /// Verifies that v1 with a regex pattern builds successfully.
    #[test]
    fn test_v1_regex_accepted() {
        let mut data = ConsumerGroupHeartbeatRequestData::new();
        data.set_subscribed_topic_regex(Some("topic-.*".to_string()));
        let builder = ConsumerGroupHeartbeatRequestBuilder::new(data);
        let built = builder.build_version(1).expect("v1 build with regex");
        match built {
            ConcreteRequest::ConsumerGroupHeartbeat(req) => {
                assert_eq!(req.version(), 1);
                assert_eq!(req.data().subscribed_topic_regex.as_deref(), Some("topic-.*"));
            },
            other => panic!("expected ConsumerGroupHeartbeat variant, got {other:?}"),
        }
    }

    /// Verifies error response carries throttle time and error code.
    #[test]
    fn test_get_error_response() {
        let mut data = ConsumerGroupHeartbeatRequestData::new();
        data.set_group_id("g1".to_string());
        let req = ConsumerGroupHeartbeatRequest::new(data, 1);
        let resp = req.get_error_response(100, &Errors::NotCoordinator);
        match resp {
            ConcreteResponse::ConsumerGroupHeartbeat(r) => {
                assert_eq!(r.throttle_time_ms(), 100);
                assert_eq!(r.error().code(), Errors::NotCoordinator.code());
            },
            other => panic!("expected ConsumerGroupHeartbeat variant, got {other:?}"),
        }
    }

    /// Verifies LEAVE_GROUP_MEMBER_EPOCH constants.
    #[test]
    fn test_constants() {
        assert_eq!(LEAVE_GROUP_MEMBER_EPOCH, -1);
        assert_eq!(LEAVE_GROUP_STATIC_MEMBER_EPOCH, -2);
        assert_eq!(JOIN_GROUP_MEMBER_EPOCH, 0);
        assert_eq!(CONSUMER_GENERATED_MEMBER_ID_REQUIRED_VERSION, 1);
    }
}
